import React,{useEffect,useState} from 'react';
import { apiJson } from '../../lib/api.js';
import { fiscalMonths,financialRatios,classifyCosts,sellingContribution,latestOperatingBreakEven,targetPacing,readFinanceWorkspace } from '../../lib/finance.js';
import './finance.css';
import FinanceOverview from './FinanceOverview.jsx';
import ProfitChart from './ProfitChart.jsx';
import FinanceTrends from './FinanceTrends.jsx';
import ProductMarginChart from './ProductMarginChart.jsx';
const percent=n=>Number.isFinite(n)?`${(n*100).toFixed(1)}%`:'—';
const dateLabel=m=>new Date(`${m}-01T12:00:00Z`).toLocaleDateString('en-US',{month:'short',year:'2-digit',timeZone:'UTC'});
const outcomes={connected:'QuickBooks connected. Save your settings, then sync reports.',invalid_state:'This connection link expired or belongs to another browser. Start Connect QuickBooks again.',authorization_declined:'QuickBooks authorization was not completed. You can connect again.',access_denied:'Only the active owner can connect QuickBooks.',connection_failed:'The connection could not be completed. Check server configuration and try again.',setup_required:'Complete the server setup before connecting.'};

export default function FinanceWorkspace(){
 const [data,setData]=useState(null),[draft,setDraft]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(()=>outcomes[new URLSearchParams(location.search).get('quickbooks')]||''),[section,setSection]=useState('overview'),[dirty,setDirty]=useState(false),[scenario,setScenario]=useState({sales:'',margin:'',fixed:''});
 const reload=async()=>{const result=readFinanceWorkspace(await apiJson('/api/finance')); setData(result);setDraft(result.settings);setDirty(false);};
 useEffect(()=>{let live=true;apiJson('/api/finance').then(readFinanceWorkspace).then(r=>{if(live){setData(r);setDraft(r.settings);}}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[]);
 useEffect(()=>{const guard=e=>{if(dirty){e.preventDefault();if(e.type==='beforeunload')e.returnValue='';}};window.addEventListener('beforeunload',guard);window.addEventListener('howl:before-tool-change',guard);return()=>{window.removeEventListener('beforeunload',guard);window.removeEventListener('howl:before-tool-change',guard);};},[dirty]);
 const update=next=>{setDraft(next);setDirty(true);};
 const run=async(action,extra={})=>{setBusy(true);setError('');setNotice('');try{const result=await apiJson('/api/finance',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...extra})});if(action==='connect'){location.assign(result.url);return;}await reload();setNotice(action==='sync'?'Reports synced successfully.':action==='save'?'Financial settings saved.':'QuickBooks disconnected from Campfire.');}catch(e){setError(e.message);}finally{setBusy(false);}};
 if(!data)return <div className="fin-workspace"><h1>Financials</h1>{error?<><p role="alert">{error}</p><button onClick={()=>{setError('');reload().catch(e=>setError(e.message));}}>Retry</button></>:<p>Loading financial workspace…</p>}</div>;
 const settings=data.settings,snapshot=data.snapshot,periods=fiscalMonths(settings.start),months=snapshot?.months||[],closed=periods.filter(m=>m<=new Date(Date.UTC(new Date().getUTCFullYear(),new Date().getUTCMonth(),0)).toISOString().slice(0,7));
 const currency=settings.currency,money=n=>Number.isFinite(n)?new Intl.NumberFormat('en-US',{style:'currency',currency,maximumFractionDigits:0}).format(n):'—';
 const totals=months.length?months.reduce((s,m)=>({revenue:s.revenue+m.revenue,cogs:s.cogs+m.cogs,netIncome:s.netIncome+m.netIncome}),{revenue:0,cogs:0,netIncome:0}):{};
 const costs=Array.isArray(settings.sellingAccountIds)?sellingContribution(snapshot?.accounts||[],settings.sellingAccountIds,months.map(m=>m.month)):classifyCosts(snapshot?.accounts||[],settings.mapping,months.map(m=>m.month));
 const ratios=financialRatios({...totals,...(snapshot?.balance||{}),...(months.length?costs:{})}),pacing=targetPacing(months,settings.targets,periods,closed.at(-1)||'');
 const breakEven=latestOperatingBreakEven(months,snapshot?.accounts||[],settings,ratios.contributionMargin);
 const scenarioSales=scenario.sales===''?breakEven.revenue:Number(scenario.sales),scenarioMargin=scenario.margin===''?ratios.contributionMargin:Number(scenario.margin)/100,scenarioFixed=scenario.fixed===''?breakEven.operatingBudget:Number(scenario.fixed);
 const scenarioReady=months.length>0&&ratios.contributionMargin!=null&&breakEven.operatingBudget!=null,scenarioBreakEven=scenarioReady&&scenarioMargin>0&&scenarioMargin<=1&&scenarioFixed>=0?scenarioFixed/scenarioMargin:null;
 const demo=import.meta.env.DEV&&import.meta.env.VITE_FINANCE_DEMO==='true';
 const save=()=>run('save',{revision:data.revision,settings:draft});
 return <div className="fin-workspace">
 <header className="fin-header"><div><span className="fin-private">Company / Private workspace</span><h1>Financials</h1><p>Your financial position. Your next decision.</p></div><div className="fin-actions"><span className="fin-owner-badge">Owner only</span>{!demo&&<button disabled={busy||dirty||!data.connection||!data.setup.ready} onClick={()=>run('sync')}>{busy?'Updating…':'Sync QuickBooks'}</button>}</div></header>
 {demo?<div className="fin-demo-banner"><div><strong>You're exploring sample data</strong><span>These are fictional figures. Your QuickBooks account is not connected.</span></div><button onClick={()=>setSection('connection')}>How to connect QuickBooks</button></div>:<div className="fin-live-status">{data.connection?(data.connection.environment==='sandbox'?'Intuit test company connected · Not your live books':'QuickBooks connected'):'QuickBooks not connected'}</div>}

 {error&&<p className="fin-alert" role="alert">{error} Your last saved reports have been kept.</p>}{notice&&<p className="fin-notice" role="status">{notice}</p>}
 {dirty&&<div className="fin-save"><span>Unsaved changes. Save to update calculations.</span><button disabled={busy} onClick={save}>Save changes</button><button disabled={busy} onClick={()=>{if(confirm('Discard unsaved financial settings?')){setDraft(data.settings);setDirty(false);}}}>Discard</button></div>}
 <nav className="fin-tabs" aria-label="Financial sections">{[['overview','Overview'],['plan','Annual plan'],['connection','Settings']].map(([id,label])=><button key={id} aria-current={section===id||(id==='connection'&&section==='costs')?'page':undefined} onClick={()=>setSection(id)}>{label}</button>)}</nav>
 {['connection','costs'].includes(section)&&<div className="fin-settings-nav"><button aria-pressed={section==='connection'} onClick={()=>setSection('connection')}>QuickBooks connection</button><button aria-pressed={section==='costs'} onClick={()=>setSection('costs')}>Cost classifications</button></div>}
 {section==='overview'&&<>
 {!snapshot?<section className="fin-empty"><div className="fin-empty-chart" aria-hidden="true">{[30,45,40,65,60,80,76,95].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div><h2>Your financial picture starts with the books.</h2><p>Connect QuickBooks, set your fiscal year, and sync completed months. Then classify costs to unlock contribution margin and break-even.</p><button onClick={()=>setSection(data.connection?'plan':'connection')}>{data.connection?'Set up your annual plan':'Set up QuickBooks'}</button><small>No accounting data connected. Illustration only.</small></section>:<>
 <FinanceOverview trends={<><ProductMarginChart periods={periods} snapshot={snapshot} settings={settings} draft={draft} update={update} save={save} busy={busy} money={money}/><FinanceTrends periods={periods} months={months} snapshot={snapshot} settings={settings} money={money} breakEven={breakEven}/></>} breakEven={breakEven} profitChart={<ProfitChart periods={periods} months={months} adjustments={settings.ebitdaAdjustments} draft={draft} update={update} save={save} busy={busy} money={money} demo={demo}/>} snapshot={snapshot} periods={periods} months={months} settings={settings} ratios={ratios} pacing={pacing} costs={costs} money={money} demo={demo} onNavigate={setSection} scenarioContent={ <details><summary>Explore a monthly scenario</summary><p>Starts from the latest reported month’s operating budget and revenue, with the year-to-date contribution margin. These assumptions do not change your plan or accounting actuals.</p><div className="fin-fields">{[['sales','Monthly sales',scenarioSales],['margin','Contribution margin %',scenarioMargin*100],['fixed','Monthly operating budget',scenarioFixed]].map(([key,label,v])=><label key={key}>{label}<input type="number" min="0" max={key==='margin'?100:undefined} step="any" value={scenario[key]} placeholder={Number.isFinite(v)?v.toFixed(1):'Classify costs first'} onChange={e=>setScenario({...scenario,[key]:e.target.value})}/></label>)}</div><p>Scenario break-even: <strong>{money(scenarioBreakEven)}</strong> · Operating result: <strong>{money(scenarioReady&&scenarioSales>=0&&scenarioMargin>=0&&scenarioMargin<=1&&scenarioFixed>=0?scenarioSales*scenarioMargin-scenarioFixed:null)}</strong></p></details>}/>

 </>}
 <aside className="fin-source-note"><h3>About these numbers</h3><p><strong>QuickBooks</strong> {demo?'will supply accounting actuals once connected. All current figures are fictional.':'supplies the accounting actuals on this page.'} <strong>Shopify</strong> continues to supply the sales dashboard. Timing, channel coverage, refunds, shipping, and taxes can differ. The two sources are never added together.</p><p>Completed calendar months are not confirmation that your accountant has closed the books. Re-sync after adjustments.</p></aside>
 </>}
 {section==='plan'&&<section className="fin-panel"><h2>Build the annual plan</h2><p>Set monthly booked-revenue targets to reflect seasonality. These targets remain separate from actuals.</p><fieldset disabled={busy}><div className="fin-fields"><label>Fiscal year starts<input type="month" min="2000-01" max="2099-12" value={draft.start} onChange={e=>{if(e.target.value)update({...draft,start:e.target.value,targets:{},ebitdaAdjustments:{}});}}/></label><label>Accounting basis<select value={draft.basis} onChange={e=>update({...draft,basis:e.target.value,ebitdaAdjustments:{}})}><option>Accrual</option><option>Cash</option></select></label><label>Plan currency<select value={draft.currency} onChange={e=>update({...draft,currency:e.target.value,ebitdaAdjustments:{}})}>{['USD','CAD','GBP','EUR','AUD','NZD'].map(c=><option key={c}>{c}</option>)}</select></label></div><p className="fin-footnote">Changing the fiscal year clears the draft targets. Changing period, basis, or currency requires a new report sync.</p><div className="fin-table-wrap"><table><thead><tr><th>Month</th><th>Revenue target ({draft.currency})</th><th>QuickBooks actual</th><th>Variance</th></tr></thead><tbody>{fiscalMonths(draft.start).map(m=>{const actual=draft.start===settings.start&&draft.basis===settings.basis&&draft.currency===settings.currency?months.find(x=>x.month===m)?.revenue:undefined;return <tr key={m}><th>{dateLabel(m)}</th><td><input aria-label={`${m} revenue target`} type="number" min="0" max="1000000000000" step="0.01" value={draft.targets[m]??''} placeholder="Not set" onChange={e=>{const targets={...draft.targets};if(e.target.value==='')delete targets[m];else targets[m]=Number(e.target.value);update({...draft,targets});}}/></td><td>{money(actual)}</td><td>{money(Number.isFinite(actual)&&Number.isFinite(draft.targets[m])?actual-draft.targets[m]:null)}</td></tr>;})}</tbody></table></div><button onClick={save}>{busy?'Saving…':'Save annual plan'}</button></fieldset></section>}
 {section==='costs'&&<section className="fin-panel"><h2>Contribution after selling expenses</h2><p>Contribution = revenue − cost of goods sold − selected selling expenses. Break-even revenue = remaining operating expenses ÷ contribution margin.</p><p>This model holds the latest reported month’s remaining operating budget constant and assumes COGS and selling expenses maintain their reported share of revenue. It excludes other income and expenses, debt principal, and capital spending.</p>{!snapshot?<p>Sync QuickBooks reports to see your accounts.</p>:<fieldset disabled={busy}><p>Select the accounts in your P&amp;L selling-expense section. All COGS are deducted automatically. Unselected operating expenses form the budget to cover.</p><div className="fin-table-wrap"><table><thead><tr><th>Account</th><th>Reported cost</th><th>Selling expense</th></tr></thead><tbody>{snapshot.accounts.filter(a=>a.group==='Expenses').map(a=><tr key={a.id}><th>{a.name}</th><td>{money(Object.values(a.values).reduce((s,n)=>s+n,0))}</td><td><input type="checkbox" aria-label={`${a.name} selling expense`} checked={(draft.sellingAccountIds||[]).includes(a.id)} onChange={e=>update({...draft,sellingAccountIds:e.target.checked?[...(draft.sellingAccountIds||[]),a.id]:(draft.sellingAccountIds||[]).filter(id=>id!==a.id)})}/></td></tr>)}</tbody></table></div><button onClick={()=>run('save',{revision:data.revision,settings:{...draft,sellingAccountIds:draft.sellingAccountIds||[]}})}>Save contribution accounts</button></fieldset>}</section>}
 {section==='connection'&&<section className="fin-panel fin-setup"><h2>Connect QuickBooks Online</h2><p><a href="/legal/terms" target="_blank" rel="noreferrer">Internal use terms</a> · <a href="/legal/privacy" target="_blank" rel="noreferrer">Financials privacy notice</a></p><p>Campfire reads the product/service item catalog and Profit & Loss and Balance Sheet reports. It does not create or edit transactions. Intuit grants an accounting scope; Campfire uses it to read these reports and, when you choose, employee and contractor names for the organizational chart.</p>{demo&&<p className="fin-demo-note">Preview mode. No Intuit app or QuickBooks account has been connected. The credentials listed below are not configured for your company.</p>}{data.connection&&!demo&&<p className="fin-notice">Connected company ID: {data.connection.realm} · {data.connection.environment}</p>}
 <ol><li><h3>Create an Intuit developer app</h3><p>Sign in to the <a href="https://developer.intuit.com" target="_blank" rel="noreferrer">Intuit developer portal</a>, create a QuickBooks Online app, and select the accounting API. Use sandbox credentials for testing and production credentials for your actual company.</p></li><li><h3>Configure the secure connection</h3><p>Your deployment administrator adds the client ID, client secret, redirect URI, environment, and a random encryption key to the server environment. Never paste secrets into this page.</p><p>Redirect URI: <code>{(!demo&&data.setup.redirectUri)||'https://welcometothecampfire.io/api/quickbooks-callback'}</code></p><ul className="fin-checks">{data.setup.checks.map(c=><li key={c.key}><span>{c.configured&&!demo?'✓ Configured':'○ Needed'}</span><code>{c.key}</code></li>)}</ul><p>Encryption key: at least 32 random characters. Environment: sandbox or production. The redirect URI must exactly match Intuit’s app settings.</p></li><li><h3>Authorize your company</h3><p>Only you, the Campfire owner, can start the connection. After authorization, return here to set the plan and sync reports.</p><button disabled={busy||dirty||demo||!data.setup.ready} onClick={()=>run('connect')}>{data.connection&&!demo?'Reconnect QuickBooks':'Connect QuickBooks'}</button>{(demo||!data.setup.ready)&&<p>Server setup is not complete or valid yet.</p>}</li></ol>
 {data.connection&&!demo&&<details><summary>Disconnect QuickBooks</summary><p>Removes Campfire’s stored credentials, report snapshot, and cost classifications. Your annual revenue targets stay saved. To revoke Intuit’s authorization as well, remove Campfire in QuickBooks Connected Apps.</p><button disabled={busy||dirty} onClick={()=>{if(confirm('Disconnect QuickBooks and remove its cached reports and account classifications from Campfire?'))run('disconnect');}}>Disconnect from Campfire</button></details>}</section>}
 </div>;
}
