import React,{useEffect,useState} from 'react';
import { apiJson } from '../../lib/api.js';
import { fiscalMonths,financialRatios,classifyCosts,targetPacing } from '../../lib/finance.js';
import './finance.css';
const percent=n=>Number.isFinite(n)?`${(n*100).toFixed(1)}%`:'—';
const dateLabel=m=>new Date(`${m}-01T12:00:00Z`).toLocaleDateString('en-US',{month:'short',year:'2-digit',timeZone:'UTC'});
const outcomes={connected:'QuickBooks connected. Save your settings, then sync reports.',invalid_state:'This connection link expired or belongs to another browser. Start Connect QuickBooks again.',authorization_declined:'QuickBooks authorization was not completed. You can connect again.',access_denied:'Only the active owner can connect QuickBooks.',connection_failed:'The connection could not be completed. Check server configuration and try again.',setup_required:'Complete the server setup before connecting.'};
function Metric({label,value,note}){return <div className="fin-metric"><span>{label}</span><strong>{value}</strong><small>{note}</small></div>;}
export default function FinanceWorkspace(){
 const [data,setData]=useState(null),[draft,setDraft]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(()=>outcomes[new URLSearchParams(location.search).get('quickbooks')]||''),[section,setSection]=useState('overview'),[dirty,setDirty]=useState(false),[scenario,setScenario]=useState({sales:'',margin:'',fixed:''});
 const reload=async()=>{const result=await apiJson('/api/finance');setData(result);setDraft(result.settings);setDirty(false);};
 useEffect(()=>{let live=true;apiJson('/api/finance').then(r=>{if(live){setData(r);setDraft(r.settings);}}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[]);
 useEffect(()=>{const guard=e=>{if(dirty){e.preventDefault();if(e.type==='beforeunload')e.returnValue='';}};window.addEventListener('beforeunload',guard);window.addEventListener('howl:before-tool-change',guard);return()=>{window.removeEventListener('beforeunload',guard);window.removeEventListener('howl:before-tool-change',guard);};},[dirty]);
 const update=next=>{setDraft(next);setDirty(true);};
 const run=async(action,extra={})=>{setBusy(true);setError('');setNotice('');try{const result=await apiJson('/api/finance',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...extra})});if(action==='connect'){location.assign(result.url);return;}await reload();setNotice(action==='sync'?'Reports synced successfully.':action==='save'?'Financial settings saved.':'QuickBooks disconnected from Campfire.');}catch(e){setError(e.message);}finally{setBusy(false);}};
 if(!data)return <div className="fin-workspace"><h1>Financials</h1>{error?<><p role="alert">{error}</p><button onClick={()=>{setError('');reload().catch(e=>setError(e.message));}}>Retry</button></>:<p>Loading financial workspace…</p>}</div>;
 const settings=data.settings,snapshot=data.snapshot,periods=fiscalMonths(settings.start),months=snapshot?.months||[],closed=periods.filter(m=>m<=new Date(Date.UTC(new Date().getUTCFullYear(),new Date().getUTCMonth(),0)).toISOString().slice(0,7));
 const currency=settings.currency,money=n=>Number.isFinite(n)?new Intl.NumberFormat('en-US',{style:'currency',currency,maximumFractionDigits:0}).format(n):'—';
 const totals=months.length?months.reduce((s,m)=>({revenue:s.revenue+m.revenue,cogs:s.cogs+m.cogs,netIncome:s.netIncome+m.netIncome}),{revenue:0,cogs:0,netIncome:0}):{};
 const costs=classifyCosts(snapshot?.accounts||[],settings.mapping,months.map(m=>m.month));
 const ratios=financialRatios({...totals,...(snapshot?.balance||{}),...(months.length?costs:{})}),pacing=targetPacing(months,settings.targets,periods,closed.at(-1)||''),max=Math.max(1,...periods.map(m=>settings.targets[m]||0),...months.map(m=>m.revenue));
 const scenarioSales=scenario.sales===''?totals.revenue/months.length:Number(scenario.sales),scenarioMargin=scenario.margin===''?ratios.contributionMargin:Number(scenario.margin)/100,scenarioFixed=scenario.fixed===''?ratios.fixedCosts/months.length:Number(scenario.fixed);
 const scenarioReady=months.length>0&&ratios.contributionMargin!=null&&ratios.fixedCosts!=null,scenarioBreakEven=scenarioReady&&scenarioMargin>0&&scenarioMargin<=1&&scenarioFixed>=0?scenarioFixed/scenarioMargin:null;
 const save=()=>run('save',{revision:data.revision,settings:draft});
 return <div className="fin-workspace">
 <header className="fin-header"><div><span className="fin-private">Owner access only</span><h1>Financials</h1><p>Turn the books into an operating plan.</p></div><div className="fin-actions"><span className={`fin-connection ${data.connection?'connected':''}`}>{data.connection?`QuickBooks ${data.connection.environment==='sandbox'?'sandbox':'connected'}`:'QuickBooks not connected'}</span><button disabled={busy||dirty||!data.connection||!data.setup.ready} onClick={()=>run('sync')}>{busy?'Working…':'Sync reports'}</button></div></header>
 {error&&<p className="fin-alert" role="alert">{error} Your last saved reports have been kept.</p>}{notice&&<p className="fin-notice" role="status">{notice}</p>}
 {dirty&&<div className="fin-save"><span>Unsaved changes. Save to update calculations.</span><button disabled={busy} onClick={save}>Save changes</button><button disabled={busy} onClick={()=>{if(confirm('Discard unsaved financial settings?')){setDraft(data.settings);setDirty(false);}}}>Discard</button></div>}
 <nav className="fin-tabs" aria-label="Financial sections">{[['overview','Financial overview'],['plan','Annual plan'],['costs','Cost classification'],['connection','Connection setup']].map(([id,label])=><button key={id} aria-current={section===id?'page':undefined} onClick={()=>setSection(id)}>{label}</button>)}</nav>
 {section==='overview'&&<>
 {!snapshot?<section className="fin-empty"><div className="fin-empty-chart" aria-hidden="true">{[30,45,40,65,60,80,76,95].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div><h2>Your financial picture starts with the books.</h2><p>Connect QuickBooks, set your fiscal year, and sync completed months. Then classify costs to unlock contribution margin and break-even.</p><button onClick={()=>setSection(data.connection?'plan':'connection')}>{data.connection?'Set up your annual plan':'Set up QuickBooks'}</button><small>No accounting data connected. Illustration only.</small></section>:<>
 <div className="fin-source"><strong>{dateLabel(months[0].month)} – {dateLabel(months.at(-1).month)}</strong><span>{snapshot.basis} basis · {snapshot.currency} · Synced {new Date(snapshot.syncedAt).toLocaleString()}</span></div>
 {snapshot.environment==='sandbox'&&<p className="fin-alert">Sandbox company. These reports are test data, not your live books.</p>}
 {pacing.missingActual.length>0&&<p className="fin-alert">{pacing.missingActual.length} completed month(s) are missing. Sync to update annual pacing.</p>}
 <div className="fin-metrics"><Metric label="Booked revenue" value={money(ratios.revenue)} note="QuickBooks P&L income"/><Metric label="Gross margin" value={percent(ratios.grossMargin)} note="(Revenue − COGS) ÷ revenue"/><Metric label="Contribution margin" value={percent(ratios.contributionMargin)} note={costs.unclassified.length?`${costs.unclassified.length} accounts need classification`:'Revenue less variable operating costs'}/><Metric label="Net margin" value={percent(ratios.netMargin)} note="QuickBooks net income ÷ revenue"/></div>
 <section className="fin-panel"><div className="fin-section-heading"><div><h2>Revenue against the plan</h2><p>Actuals and targets for each fiscal month. Open months have no accounting actuals here.</p></div><strong className={pacing.variance==null?'':pacing.variance<0?'fin-negative':'fin-positive'}>{pacing.variance==null?'Set monthly targets':`${money(Math.abs(pacing.variance))} ${pacing.variance<0?'behind':'ahead of'} plan`}</strong></div>
 <div className="fin-legend"><span>● QuickBooks actual</span><span>○ Monthly target</span></div><div className="fin-chart" role="img" aria-label="Monthly revenue compared with targets; exact values are in Annual plan">{periods.map(m=>{const actual=months.find(x=>x.month===m)?.revenue;return <div key={m} className="fin-chart-column" title={`${m}: actual ${money(actual)}, target ${money(settings.targets[m])}`}><div className="fin-bars"><i style={{height:`${Math.max(0,actual||0)/max*100}%`}}/><i style={{height:`${(settings.targets[m]||0)/max*100}%`}}/></div><small>{dateLabel(m)}</small></div>;})}</div><p className="fin-footnote">Negative revenue is shown as zero-height in the chart; exact signed values are in Annual plan.</p>
 <div className="fin-metrics"><Metric label="Completed-month plan" value={money(pacing.planToDate)} note={`${pacing.closedMonths} completed months`}/><Metric label="Annual target achieved" value={percent(pacing.attainment)} note={`Annual target: ${money(pacing.annualTarget)}`}/><Metric label="Required per remaining month" value={money(pacing.requiredMonthly)} note={`${pacing.remainingMonths} remaining months`}/><Metric label="Actual + remaining plan" value={money(pacing.actualPlusRemainingPlan)} note="Scenario, not a predictive forecast"/></div></section>
 <section className="fin-panel"><h2>Operating break-even</h2><p>For the same {months.length}-month period as the reports. Excludes non-operating income and costs.</p>{costs.unclassified.length?<p className="fin-alert">Classify {costs.unclassified.length} cost accounts before using this calculation. <button onClick={()=>setSection('costs')}>Review accounts</button></p>:<div className="fin-metrics"><Metric label="Contribution" value={money(ratios.contribution)} note="Revenue − variable costs"/><Metric label="Fixed operating costs" value={money(ratios.fixedCosts)} note="Based on your classifications"/><Metric label="Break-even revenue" value={money(ratios.breakEvenSales)} note={ratios.contributionMargin>0?'Fixed costs ÷ contribution margin':'Requires a positive contribution margin'}/><Metric label="Revenue above / below break-even" value={money(ratios.marginOfSafety)} note="Actual revenue − break-even revenue"/></div>}
 <details><summary>Explore a monthly scenario</summary><p>Starts from the synced monthly average. These assumptions do not change your plan or accounting actuals.</p><div className="fin-fields">{[['sales','Monthly sales',scenarioSales],['margin','Contribution margin %',scenarioMargin*100],['fixed','Monthly fixed costs',scenarioFixed]].map(([key,label,v])=><label key={key}>{label}<input type="number" min="0" max={key==='margin'?100:undefined} step="any" value={scenario[key]} placeholder={Number.isFinite(v)?v.toFixed(1):'Classify costs first'} onChange={e=>setScenario({...scenario,[key]:e.target.value})}/></label>)}</div><p>Scenario break-even: <strong>{money(scenarioBreakEven)}</strong> · Operating result: <strong>{money(scenarioReady&&scenarioSales>=0&&scenarioMargin>=0&&scenarioMargin<=1&&scenarioFixed>=0?scenarioSales*scenarioMargin-scenarioFixed:null)}</strong></p></details></section>
 <section className="fin-panel"><h2>Balance-sheet health</h2><p>As of {snapshot.balance.asOf}. Missing report groups or nonpositive denominators show as unavailable.</p><div className="fin-metrics">{[['Current ratio',ratios.currentRatio,'Current assets ÷ current liabilities'],['Quick ratio',ratios.quickRatio,'(Bank accounts + receivables) ÷ current liabilities'],['Liabilities to equity',ratios.debtToEquity,'Total liabilities ÷ equity']].map(([label,v,note])=><Metric key={label} label={label} value={v==null?'—':`${v.toFixed(2)}×`} note={note}/>)}</div></section>
 </>}
 <aside className="fin-source-note"><h3>One business, two reporting views</h3><p><strong>QuickBooks</strong> supplies the accounting actuals on this page. <strong>Shopify</strong> continues to supply the sales dashboard. Timing, channel coverage, refunds, shipping, and taxes can differ. The two sources are never added together.</p><p>Completed calendar months are not confirmation that your accountant has closed the books. Re-sync after adjustments.</p></aside>
 </>}
 {section==='plan'&&<section className="fin-panel"><h2>Build the annual plan</h2><p>Set monthly booked-revenue targets to reflect seasonality. These targets remain separate from actuals.</p><fieldset disabled={busy}><div className="fin-fields"><label>Fiscal year starts<input type="month" min="2000-01" max="2099-12" value={draft.start} onChange={e=>{if(e.target.value)update({...draft,start:e.target.value,targets:{}});}}/></label><label>Accounting basis<select value={draft.basis} onChange={e=>update({...draft,basis:e.target.value})}><option>Accrual</option><option>Cash</option></select></label><label>Plan currency<select value={draft.currency} onChange={e=>update({...draft,currency:e.target.value})}>{['USD','CAD','GBP','EUR','AUD','NZD'].map(c=><option key={c}>{c}</option>)}</select></label></div><p className="fin-footnote">Changing the fiscal year clears the draft targets. Changing period, basis, or currency requires a new report sync.</p><div className="fin-table-wrap"><table><thead><tr><th>Month</th><th>Revenue target ({draft.currency})</th><th>QuickBooks actual</th><th>Variance</th></tr></thead><tbody>{fiscalMonths(draft.start).map(m=>{const actual=draft.start===settings.start&&draft.basis===settings.basis&&draft.currency===settings.currency?months.find(x=>x.month===m)?.revenue:undefined;return <tr key={m}><th>{dateLabel(m)}</th><td><input aria-label={`${m} revenue target`} type="number" min="0" max="1000000000000" step="0.01" value={draft.targets[m]??''} placeholder="Not set" onChange={e=>{const targets={...draft.targets};if(e.target.value==='')delete targets[m];else targets[m]=Number(e.target.value);update({...draft,targets});}}/></td><td>{money(actual)}</td><td>{money(Number.isFinite(actual)&&Number.isFinite(draft.targets[m])?actual-draft.targets[m]:null)}</td></tr>;})}</tbody></table></div><button onClick={save}>{busy?'Saving…':'Save annual plan'}</button></fieldset></section>}
 {section==='costs'&&<section className="fin-panel"><h2>Classify operating costs</h2><p>Variable costs move with sales or production. Fixed costs remain within your operating range. Split mixed accounts using the variable percentage. Review manufacturing labor, freight, merchant fees, and overhead with your accountant.</p><p>These rules apply to every synced month. Changing them recalculates contribution and break-even without changing QuickBooks.</p>{!snapshot?<p>Sync QuickBooks reports to see your actual cost accounts.</p>:<fieldset disabled={busy}><div className="fin-table-wrap"><table><thead><tr><th>Account</th><th>Reported cost</th><th>Variable portion</th><th>Fixed portion</th></tr></thead><tbody>{snapshot.accounts.map(a=>{const v=draft.mapping[a.id]?.variablePct;return <tr key={a.id}><th>{a.name}<small>{a.group==='COGS'?'Cost of goods sold':'Operating expenses'}</small></th><td>{money(Object.values(a.values).reduce((s,n)=>s+n,0))}</td><td><label className="fin-percent"><input aria-label={`${a.name} variable percentage`} type="number" min="0" max="100" step="any" placeholder="Unclassified" value={v??''} onChange={e=>{const mapping={...draft.mapping};if(e.target.value==='')delete mapping[a.id];else mapping[a.id]={variablePct:Number(e.target.value)};update({...draft,mapping});}}/>%</label></td><td>{v==null?'—':`${100-v}%`}</td></tr>;})}</tbody></table></div><button onClick={save}>Save classifications</button></fieldset>}</section>}
 {section==='connection'&&<section className="fin-panel fin-setup"><h2>Connect QuickBooks Online</h2><p>Campfire reads Profit & Loss and Balance Sheet reports. It does not create or edit transactions. Intuit grants an accounting scope; Campfire uses it only to read these reports.</p>{data.connection&&<p className="fin-notice">Connected company ID: {data.connection.realm} · {data.connection.environment}</p>}
 <ol><li><h3>Create an Intuit developer app</h3><p>Sign in to the <a href="https://developer.intuit.com" target="_blank" rel="noreferrer">Intuit developer portal</a>, create a QuickBooks Online app, and select the accounting API. Use sandbox credentials for testing and production credentials for your actual company.</p></li><li><h3>Configure the secure connection</h3><p>Your deployment administrator adds the client ID, client secret, redirect URI, environment, and a random encryption key to the server environment. Never paste secrets into this page.</p><p>Redirect URI: <code>{data.setup.redirectUri||`${location.origin}/api/quickbooks-callback`}</code></p><ul className="fin-checks">{data.setup.checks.map(c=><li key={c.key}><span>{c.configured?'✓ Configured':'○ Needed'}</span><code>{c.key}</code></li>)}</ul><p>Encryption key: at least 32 random characters. Environment: sandbox or production. The redirect URI must exactly match Intuit’s app settings.</p></li><li><h3>Authorize your company</h3><p>Only you, the Campfire owner, can start the connection. After authorization, return here to set the plan and sync reports.</p><button disabled={busy||dirty||!data.setup.ready} onClick={()=>run('connect')}>{data.connection?'Reconnect QuickBooks':'Connect QuickBooks'}</button>{!data.setup.ready&&<p>Server setup is not complete or valid yet.</p>}</li></ol>
 {data.connection&&<details><summary>Disconnect QuickBooks</summary><p>Removes Campfire’s stored credentials, report snapshot, and cost classifications. Your annual revenue targets stay saved. To revoke Intuit’s authorization as well, remove Campfire in QuickBooks Connected Apps.</p><button disabled={busy||dirty} onClick={()=>{if(confirm('Disconnect QuickBooks and remove its cached reports and account classifications from Campfire?'))run('disconnect');}}>Disconnect from Campfire</button></details>}</section>}
 </div>;
}
