import React, { useEffect, useState } from 'react';
const HOOKS={primary:'Primary script',first:'Opening 1',second:'Opening 2',third:'Opening 3',custom:'Custom / edited opening'};
const num=v=>v==null?'—':Number(v).toLocaleString(undefined,{maximumFractionDigits:2});
const pct=v=>v==null?'—':`${(v*100).toFixed(1)}%`;
export default function ScriptPerformance({savedId,request,canLink=false}) {
  const [days,setDays]=useState(30),[data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[adId,setAdId]=useState(''),[variant,setVariant]=useState('primary'),[query,setQuery]=useState(''),[ads,setAds]=useState([]),[reload,setReload]=useState(0);
  useEffect(()=>{let active=true;setData(null);setError('');setLoading(true);request(`/api/script-studio?action=performance&id=${savedId}&days=${days}`).then(d=>{if(active)setData(d);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[savedId,days,reload,request]);
  async function findAds(e){e.preventDefault();setBusy(true);setError('');try{const d=await request(`/api/script-studio?action=ads&q=${encodeURIComponent(query)}`);setAds(d.ads);}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function link(e){e.preventDefault();setBusy(true);setError('');try{await request('/api/script-studio',{action:'link_ad',id:savedId,ad_id:adId,hook_variant:variant});setAdId('');setReload(n=>n+1);}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function unlink(id){setBusy(true);setError('');try{await request('/api/script-studio',{action:'unlink_ad',id:savedId,ad_id:id});setReload(n=>n+1);}catch(e){setError(e.message);}finally{setBusy(false);}}
  const t=data?.totals;
  return <section className="ss-performance"><div className="ss-performance-head"><h3>Performance of this saved version</h3><label>Window<select value={days} onChange={e=>setDays(Number(e.target.value))}>{[7,30,90].map(n=><option key={n} value={n}>Last {n} days</option>)}</select></label><button type="button" disabled={loading} onClick={()=>setReload(n=>n+1)}>Refresh results</button></div>
    <p className="ss-help">Meta-reported results for explicitly linked ads. Linking does not launch or change an ad. Amounts use the Meta ad account’s currency.</p>
    {error&&<p role="alert" className="ss-error">{error}</p>}{loading&&<p role="status">Loading script performance…</p>}
    {t&&<><div className="ss-metrics">{[['Spend',num(t.spend)],['Purchases',num(t.purchases)],['CPA',num(t.cpa)],['ROAS',t.roas==null?'—':`${t.roas.toFixed(2)}×`],['CTR',pct(t.ctr)],['Hook rate',pct(t.hook_rate)],['Hold rate',pct(t.hold_rate)]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>
    {!data.ads.length?<p>No ads linked yet. Save the script version used in production, then link the ads running it.</p>:!t.has_data?<p>Ads are linked, but there are no synced results in this window. This is not a zero-performance result.</p>:<p className="ss-help">Last synced {t.last_synced?new Date(t.last_synced).toLocaleString():'unknown'}. Refresh reads Campfire’s latest sync; run Meta sync in Creative Analytics if results are stale.</p>}
    <p className="ss-help">CTR = all clicks ÷ impressions. Hook rate = 3-second views ÷ impressions. Hold rate = ThruPlays ÷ 3-second views; ThruPlay means 15 seconds or completion for shorter videos. CPA is purchase cost, not new-customer acquisition cost. These are ad outcomes, not proof that one script element caused them.</p>
    {data.variants.length>0&&<div className="ss-table"><table><caption>Results by opening used</caption><thead><tr><th>Opening</th><th>Ads</th><th>Spend</th><th>Purchases</th><th>CPA</th><th>ROAS</th><th>Hook</th><th>Hold</th></tr></thead><tbody>{data.variants.map(v=><tr key={v.variant}><td>{HOOKS[v.variant]}</td><td>{v.ads}</td><td>{num(v.spend)}</td><td>{num(v.purchases)}</td><td>{num(v.cpa)}</td><td>{num(v.roas)}</td><td>{pct(v.hook_rate)}</td><td>{pct(v.hold_rate)}</td></tr>)}</tbody></table></div>}
    {data.ads.map(ad=><div className="ss-linked-ad" key={ad.ad_id}><div><strong>{ad.ad_name||ad.ad_id}</strong><p>{ad.ad_id} · {HOOKS[ad.hook_variant]} · {ad.has_data?`${num(ad.spend)} spend / ${num(ad.purchases)} purchases`:'No synced data in this window'}</p></div>{canLink&&<button disabled={busy} onClick={()=>unlink(ad.ad_id)}>Unlink</button>}</div>)}</>}
    {canLink&&<details className="ss-detail"><summary>Link an ad to this version</summary><p>Choose the version and opening actually filmed. Only link ads that used this version throughout the reporting window.</p>
      <form onSubmit={findAds} className="ss-inline-form"><label>Find a launched ad<input value={query} maxLength={200} onChange={e=>setQuery(e.target.value)} placeholder="Ad name or ID" /></label><button disabled={busy}>Search ads</button></form>
      {ads.length>0&&<label className="ss-field">Search results<select value="" onChange={e=>setAdId(e.target.value)}><option value="">Choose an ad</option>{ads.map(ad=><option key={ad.ad_id} value={ad.ad_id} disabled={!!ad.script_id&&ad.script_id!==savedId}>{ad.ad_name||ad.ad_id} · {ad.ad_id}{ad.script_id?' (already linked)':''}</option>)}</select></label>}
      <form onSubmit={link} className="ss-inline-form"><label>Meta ad ID<input required pattern="[0-9]{5,40}" value={adId} onChange={e=>setAdId(e.target.value.trim())} placeholder="Or paste a synced Meta ad ID" /></label><label>Opening actually used<select value={variant} onChange={e=>setVariant(e.target.value)}>{Object.entries(HOOKS).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><button disabled={busy}>Link ad</button></form>
    </details>}
  </section>;
}
