// Isolated browser/API/PostgreSQL verification. Uses no live accounts or data.
import { createRequire } from 'node:module';
import { createServer } from 'vite';
import react from '@vitejs/plugin-react';
import { PGlite } from '@electric-sql/pglite';
import { useTestDatabase } from '../tests/neon-test-adapter.mjs';
import { initializeSchema } from '../api/db/schema.js';
import handler from '../api/creator-seeding-log.js';
import intakeHandler from '../api/creator-investment-intake.js';
import creatorsHandler from '../api/creators.js';
import feesHandler from '../api/creator-fees.js';
import path from 'node:path';
import { mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
const require = createRequire(import.meta.url);
const { chromium } = require(path.join(process.env.SEED_QA_RUNTIME, 'playwright'));
process.env.NODE_ENV='development'; process.env.AUTH_DISABLED='true'; process.env.DATABASE_URL='postgresql://test:test@fixture.local/test';
const db=new PGlite(), restore=useTestDatabase(db);
const sql=async(parts,...values)=>(await db.query(parts.reduce((q,p,i)=>q+(i?`$${i}`:'')+p,''),values)).rows;
const output='/private/tmp/howl-seeding-qa'; await mkdir(output,{recursive:true});
let server,browser;
try {
  await initializeSchema(sql);
  await db.exec(`INSERT INTO creators(id,name) VALUES (98765,'QA creator');
    INSERT INTO creator_seeding_log(creator_id,seeded_on,unit_cogs,quantity,shipping_cost,creator_fee)
    VALUES (98765,'2024-04-05',100,2,20,50),(98765,'2026-04-05',100,1,20,0),(98765,'2026-05-05',200,1,20,0),(98765,'2026-06-05',300,1,20,0),(98765,'2026-07-05',400,1,20,50),(98765,'2026-08-05',1200,2,150,1000),(98765,'2026-09-01',1000,1,75,500);
    INSERT INTO launch_history(ad_id,creator_id) VALUES ('qa-ad',98765);
    INSERT INTO creative_insights_daily(ad_id,date,spend,purchase_value) VALUES ('qa-ad','2026-08-06',1000,10000),('qa-unreviewed','2026-08-06',3000,20000);`);
  const entry=`import React from 'react';import {createRoot} from 'react-dom/client';import Ledger from '/src/components/SeedingLedger.jsx';import '/src/styles.css';createRoot(document.getElementById('root')).render(<Ledger canManage={new URLSearchParams(location.search).get('readonly')!=='true'}/>);`;
  server=await createServer({configFile:false,root:process.cwd(),envDir:path.join(output,'empty-env'),optimizeDeps:{exclude:['@clerk/clerk-react'],force:true},plugins:[react(),{
    name:'seeding-qa',enforce:'pre',resolveId(id){if(id==='@clerk/clerk-react')return '\0qa-clerk';if(id==='/fixture.jsx')return path.join(process.cwd(),'__seeding_qa__.jsx')},load(id){if(id==='\0qa-clerk')return 'export const useAuth=()=>({getToken:async()=>null});';if(id.endsWith('__seeding_qa__.jsx'))return entry},configureServer(s){s.middlewares.use(async(req,res,next)=>{
      if(req.url==='/' || req.url.startsWith('/?')){res.setHeader('Content-Type','text/html');return res.end(await s.transformIndexHtml('/', '<html><head><meta name="viewport" content="width=device-width,initial-scale=1"></head><body ><main id="root"></main><script type="module" src="/fixture.jsx"></script></body></html>'))}
      if(!req.url.startsWith('/api/'))return next();
      const chunks=[];for await(const chunk of req)chunks.push(chunk);req.body=chunks.length?JSON.parse(Buffer.concat(chunks)):{};req.query={};res.status=n=>{res.statusCode=n;return res};res.json=value=>{res.setHeader('Content-Type','application/json');res.end(JSON.stringify(value))};
      if(req.url.startsWith('/api/creator-investment-intake'))return intakeHandler(req,res);
      if(req.url.startsWith('/api/creators'))return creatorsHandler(req,res);
      if(req.url.startsWith('/api/creator-fees'))return feesHandler(req,res);
      if(req.url.startsWith('/api/shopify-products'))return res.json({connected:false,products:[]});
      await handler(req,res);
    })}
  }],server:{host:'127.0.0.1',port:5189,strictPort:true}}); await server.listen();
  browser=await chromium.launch({headless:true,channel:'chrome'});const page=await browser.newPage({viewport:{width:1440,height:1100}}),errors=[];page.on('pageerror',e=>{errors.push(e.message);console.error('Browser error:',e.message)});page.on('console',m=>{if(m.type()==='error')console.error(m.text())});
  await page.goto('http://127.0.0.1:5189');await page.getByRole('heading',{name:'Monthly investment',exact:true}).waitFor();
  await page.getByRole('button',{name:'Apr 2024:',exact:false}).click();
  assert.ok(await page.getByText('$220',{exact:true}).count());
  assert.ok(await page.getByRole('button',{name:'Aug 2026:',exact:false}).count());
  await page.getByRole('button',{name:'Aug 2026:',exact:false}).click();
  await page.getByRole('heading',{name:'Creator linking coverage',exact:true}).waitFor();
  assert.ok(await page.getByText('1 of 2 ads with spend are linked to creators · 25.0% of account spend.',{exact:false}).count());
  assert.ok(await page.getByText('Partial attribution:',{exact:false}).count());
  assert.equal(await page.getByRole('link',{name:'Review ad sources'}).getAttribute('href'),'/?tab=creative-analytics');
  await page.getByRole('button',{name:'Edit budgets'}).click();
  await page.getByLabel('Seeding budget ($)').fill('4000');await page.getByLabel('Creator fee budget ($)').fill('2000');
  await page.getByRole('button',{name:'Save for Aug 2026'}).click();await page.getByRole('button',{name:'Edit budgets'}).waitFor();
  assert.equal((await db.query("SELECT seeding FROM creator_monthly_budgets WHERE month='2026-08'")).rows[0].seeding,'4000.00');
  assert.ok(await page.getByText('$1,450',{exact:true}).count());
  assert.ok(await page.getByText('10.00×',{exact:true}).count());
  assert.ok(await page.getByText('119.8%',{exact:true}).count());
  const invalid=await page.request.patch('http://127.0.0.1:5189/api/creator-seeding-log',{data:{action:'budget',month:'2026-13',seeding:-1,creator:0}});assert.equal(invalid.status(),400);
  await page.screenshot({path:path.join(output,'desktop.png'),fullPage:true});
  await page.reload();await page.getByRole('button',{name:'Aug 2026:',exact:false}).click();assert.ok(await page.getByText('$1,450',{exact:true}).count());
  await page.getByLabel('View month').fill('2026-07');await page.getByText('No linked ad data for this month').waitFor();
  assert.equal(await page.getByText('budget not set',{exact:true}).count(),2);
  await page.getByRole('button',{name:'Add creator or investment'}).click();
  await page.getByLabel('Creator name',{exact:true}).fill('Ted QA New Creator');
  await page.getByLabel('Contact',{exact:true}).fill('creator@example.test');
  await page.getByLabel('Seeded on',{exact:true}).fill('2026-08-10');
  await page.getByLabel('Qty',{exact:true}).fill('2');
  await page.getByLabel('Seed item',{exact:true}).selectOption('unit:R1');
  assert.equal(await page.getByLabel('Qty',{exact:true}).inputValue(),'2');
  await page.getByLabel('Unit COGS',{exact:true}).fill('125');
  await page.getByLabel('Shipping',{exact:true}).fill('25');
  await page.getByLabel('Compensation',{exact:true}).fill('300');
  await page.getByLabel('Assets owed',{exact:true}).fill('2');
  await page.getByLabel('Due date',{exact:true}).fill('2026-08-25');
  await page.getByLabel('Usage rights',{exact:true}).fill('Paid social for 12 months');
  await page.getByRole('button',{name:'Save investment',exact:true}).click();
  const newRow=page.getByRole('row').filter({hasText:'Ted QA New Creator'});await newRow.waitFor();
  assert.equal(await page.getByLabel('Ledger month').inputValue(),'2026-08');
  const created=(await db.query("SELECT id FROM creators WHERE name='Ted QA New Creator'")).rows[0];assert.ok(created);
  let saved=(await db.query('SELECT * FROM creator_seeding_log WHERE creator_id=$1',[created.id])).rows[0];
  assert.equal(Number(saved.quantity),2);assert.equal(Number(saved.creator_fee),300);
  assert.equal(Number((await db.query('SELECT fee_amount FROM creator_engagements WHERE creator_id=$1',[created.id])).rows[0].fee_amount),300);
  assert.ok((await db.query('SELECT id FROM creator_deliverables WHERE creator_id=$1',[created.id])).rows.length);
  await newRow.getByRole('button',{name:'Edit',exact:true}).click();
  assert.equal(await page.getByLabel('Seeded date',{exact:true}).inputValue(),'2026-08-10');
  assert.equal(await page.getByLabel('Deliverable due date',{exact:true}).inputValue(),'2026-08-25');
  await page.getByPlaceholder('Shipping',{exact:true}).fill('40');
  await page.getByRole('button',{name:'Save changes',exact:true}).click();await newRow.getByRole('button',{name:'Edit',exact:true}).waitFor();
  saved=(await db.query('SELECT shipping_cost FROM creator_seeding_log WHERE creator_id=$1',[created.id])).rows[0];assert.equal(Number(saved.shipping_cost),40);
  await page.getByRole('button',{name:'Add creator or investment'}).click();
  await page.getByLabel('Creator record').selectOption(String(created.id));
  await page.getByLabel('Seeded on',{exact:true}).fill('2026-08-11');
  await page.getByLabel('Compensation',{exact:true}).fill('100');
  await page.getByRole('button',{name:'Save investment',exact:true}).click();
  await page.getByRole('button',{name:'Add creator or investment'}).waitFor();
  assert.equal((await db.query("SELECT id FROM creators WHERE name='Ted QA New Creator'")).rows.length,1);
  assert.equal((await db.query('SELECT id FROM creator_seeding_log WHERE creator_id=$1',[created.id])).rows.length,2);
  await page.screenshot({path:path.join(output,'desktop.png'),fullPage:true});
  await page.getByRole('button',{name:'Add creator or investment'}).click();
  await page.screenshot({path:path.join(output,'intake.png'),fullPage:true});
  await page.getByRole('button',{name:'Close intake'}).click();
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(output,'mobile.png'),fullPage:true});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.goto('http://127.0.0.1:5189/?readonly=true');await page.getByRole('heading',{name:'Monthly investment',exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Add creator or investment'}).count(),0);assert.deepEqual(errors,[]);
  console.log('PASS: full ledger with fee notes, new creator intake, existing creator investment, costs, engagement, deliverables, edit, budget save/reload, month drilldown, read-only UI, desktop/mobile, no browser errors. Screenshots: '+output);
} finally {await browser?.close();await server?.close();restore();await db.close();}
