import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { apiJson } from '../../lib/api.js';
import { dayString, emptyWorkspace, metricHealth, objectiveProgress, initiativeHealth, formatValue, scorecardCsv, LABELS, constraintHealth, constraintsForMetric, cycleLevel } from '../../lib/coo.js';
import CooOperating, { ConstraintList } from './CooOperating.jsx';
import CooEditor from './CooEditor.jsx';
import CooTargets from './CooTargets.jsx';
import './coo.css';
const VIEWS=[['targets','Department targets'],['overview','Operating view'],['plan','Plan'],['constraints','Constraints & actions'],['reviews','Weekly review']];
const collections={department:'departments',cycle:'cycles',objective:'objectives',metric:'metrics',initiative:'initiatives',review:'reviews',constraint:'constraints'};
const Badge=({status})=><span className={`coo-badge coo-${status}`}>{LABELS[status]||status}</span>;
const Empty=({children})=><div className="coo-empty">{children}</div>;
function Trend({state,item}) {
  const points=state.checkins.filter(c=>c.kind==='metric'&&c.entityId===item.id).sort((a,b)=>a.date.localeCompare(b.date)||a.createdAt.localeCompare(b.createdAt));
  const unique=[...new Map(points.map(c=>[c.date,c])).values()].slice(-12);
  if(unique.length<2)return <span className="coo-muted">Need 2 updates</span>;
  const low=Math.min(item.target,...unique.map(c=>c.value)),high=Math.max(item.target,...unique.map(c=>c.value));
  const y=v=>32-(v-low)/(high-low||1)*26;
  return <svg className="coo-trend" viewBox="0 0 116 38" role="img" aria-label={`Last ${unique.length} updates, ${formatValue(unique[0].value,item.unit)} to ${formatValue(unique.at(-1).value,item.unit)}`}><line x1="2" x2="114" y1={y(item.target)} y2={y(item.target)} stroke="#aaa" strokeDasharray="3 3"/><polyline fill="none" stroke="currentColor" strokeWidth="2" points={unique.map((c,i)=>`${3+i*110/(unique.length-1)},${y(c.value)}`).join(' ')}/></svg>;
}
export default function CooWorkspace({setActiveTab}) {
  const [data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
  const [planView,setPlanView]=useState('strategy');
  const [view,setView]=useState('targets'),[cycleId,setCycleId]=useState(''),[departmentId,setDepartmentId]=useState(''),[query,setQuery]=useState(''),[statusFilter,setStatusFilter]=useState('');
  const [editor,setEditor]=useState(null),[detail,setDetail]=useState(null),[notice,setNotice]=useState(''),[includeArchived,setIncludeArchived]=useState(false);
  const lock=useRef(false),initialized=useRef(false);
  const load=useCallback(async()=>{if(lock.current)return;setLoading(true);setError('');try{const result=await apiJson('/api/coo-workspace');setData(result);if(!initialized.current){const today=dayString();const cycles=result.state.cycles.filter(c=>!c.archived);setCycleId(cycles.find(c=>c.start<=today&&c.end>=today&&c.parentId)?.id||cycles.find(c=>c.start<=today&&c.end>=today)?.id||cycles.at(-1)?.id||'');initialized.current=true;}}catch(e){setError(e.message);}finally{setLoading(false);}},[]);
  useEffect(()=>{load();},[load]);
  const state=useMemo(()=>({...emptyWorkspace(),...data?.state}),[data]);
  const today=dayString(),canWrite=!!data?.canWrite;
  const cycle=state.cycles.find(c=>c.id===cycleId);
  const visible=item=>(includeArchived||!item.archived)&&(!cycleId||item.cycleId===cycleId)&&(!departmentId||item.departmentId===departmentId)&&(!query||`${item.title} ${item.owner} ${item.description}`.toLowerCase().includes(query.toLowerCase()));
  const metrics=state.metrics.filter(visible),objectives=state.objectives.filter(visible),initiatives=state.initiatives.filter(visible),reviews=state.reviews.filter(visible);
  const constraints=state.constraints.filter(c=>(includeArchived||!c.archived)&&(!cycleId||c.cycleId===cycleId)&&(!departmentId||c.departmentId===departmentId||c.metricIds?.some(id=>state.metrics.find(m=>m.id===id)?.departmentId===departmentId)||c.objectiveIds?.some(id=>state.objectives.find(o=>o.id===id)?.departmentId===departmentId))&&(!query||`${c.title} ${c.owner} ${c.impact} ${c.decision}`.toLowerCase().includes(query.toLowerCase())));
  const departments=state.departments.filter(d=>!d.archived&&(!departmentId||d.id===departmentId));
  const name=(key,id,fallback='Company-wide')=>state[key].find(x=>x.id===id)?.name||state[key].find(x=>x.id===id)?.title||fallback;
  const defaults={cycleId:cycle?.archived?'':cycleId,departmentId:departmentId||state.departments.find(d=>!d.archived)?.id||''};
  const open=(kind,item,mode='save',extra={})=>{setError('');setEditor({kind,item,mode,defaults:{...defaults,...extra}});};
  const mutate=async(command)=>{
    if(lock.current||loading)return false;lock.current=true;setBusy(true);setError('');setNotice('');
    try{const result=await apiJson('/api/coo-workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:data.revision,command})});setData(result);setEditor(null);setNotice(command.action==='archive'?'Archived. History is preserved.':command.action==='checkin'?'Check-in saved.':'Saved to the COO workspace.');if(command.kind==='cycle'&&!command.id)setCycleId(result.state.cycles.at(-1).id);return true;}
    catch(e){setError(e.message);return false;}finally{lock.current=false;setBusy(false);}
  };
  const archive=(kind,item)=>{if(window.confirm(`Archive “${item.name||item.title}”? Its history will remain available.`))mutate({action:'archive',kind,id:item.id,expectedVersion:item.version||1});};
  const editButtons=(kind,item)=><div className="coo-row-actions"><button onClick={()=>setDetail({kind,id:item.id})}>Details</button>{canWrite&&!item.archived&&<>{kind!=='review'&&<button onClick={()=>open(kind,item)}>Edit</button>}{['metric','initiative','constraint'].includes(kind)&&<button onClick={()=>open(kind,item,'checkin')}>Update progress</button>}</>}</div>;
  const activeMetrics=metrics.filter(m=>!m.archived),activeInitiatives=initiatives.filter(i=>!i.archived);
  const exceptions=[...activeMetrics.map(item=>({kind:'metric',item,...metricHealth(state,item,today)})),...constraints.filter(c=>!c.archived&&constraintHealth(state,c,today).reportedStatus!=='resolved').map(item=>({kind:'constraint',item,...constraintHealth(state,item,today)})),...activeInitiatives.map(item=>({kind:'initiative',item,...initiativeHealth(state,item,today)}))].filter(x=>['at-risk','off-track','stale','no-data','no-plan','no-forecast','blocked','overdue','open','in-progress'].includes(x.status));
  const filteredMetrics=metrics.filter(m=>!statusFilter||metricHealth(state,m,today).status===statusFilter);
  const detailItem=detail&&state[collections[detail.kind]].find(i=>i.id===detail.id);
  const exportCsv=()=>{const url=URL.createObjectURL(new Blob([scorecardCsv(state,filteredMetrics,today)],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download=`campfire-scorecard-${today}.csv`;a.click();URL.revokeObjectURL(url);};
  if(!data)return <div className="coo-page">{loading?<p role="status">Loading COO workspace…</p>:<div className="coo-error" role="alert">{error}<button onClick={load}>Retry</button></div>}</div>;
  return <div className="coo-page">
    <header className="coo-head"><div><h1>COO workspace</h1><p>Annual direction. Quarterly priorities. Monthly results.</p></div><div className="coo-head-actions"><span>{canWrite?'Private · owner only':'Read-only access'}</span><button onClick={()=>setView('planning')}>Setup</button><button onClick={load} disabled={loading||busy}>{loading?'Refreshing…':'Refresh'}</button></div></header>
    <nav className="coo-tabs" aria-label="COO sections">{VIEWS.map(([id,label])=><button key={id} aria-current={view===id?'page':undefined} className={view===id?'active':''} onClick={()=>{setView(id);setQuery('');setStatusFilter('');}}>{label}</button>)}</nav>
    {view==='plan'&&<nav className="coo-plan-tabs" aria-label="Plan sections">{[['strategy','Goals & objectives'],['scorecards','Measures & checkpoints']].map(([id,label])=><button key={id} className={planView===id?'active':''} onClick={()=>setPlanView(id)}>{label}</button>)}</nav>}
    {view==='targets'&&<nav className="coo-plan-tabs" aria-label="Target periods">{['annual','quarterly','monthly'].map(level=><button key={level} className={cycleLevel(cycle)===level?'active':''} onClick={()=>{const options=state.cycles.filter(c=>!c.archived&&cycleLevel(c)===level);const match=options.find(c=>c.start<=today&&c.end>=today)||options.at(-1);if(match)setCycleId(match.id);else if(canWrite)open('cycle',null,'save',{level});}}>{level[0].toUpperCase()+level.slice(1)}</button>)}</nav>}
    <div className="coo-toolbar"><label>Planning cycle<select value={cycleId} onChange={e=>setCycleId(e.target.value)}><option value="">All cycles</option>{state.cycles.filter(c=>!c.archived||includeArchived).map(c=><option key={c.id} value={c.id}>{c.name}{c.archived?' (archived)':''}</option>)}</select></label><label>Department<select value={departmentId} onChange={e=>setDepartmentId(e.target.value)}><option value="">All departments</option>{state.departments.filter(d=>!d.archived||includeArchived).map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label className="coo-search">Search<input type="search" placeholder="Title, owner, or description" value={query} onChange={e=>setQuery(e.target.value)}/></label>{view!=='targets'&&<label className="coo-checkbox"><input type="checkbox" checked={includeArchived} onChange={e=>{setIncludeArchived(e.target.checked);if(!e.target.checked){if(cycle?.archived)setCycleId('');if(state.departments.find(d=>d.id===departmentId)?.archived)setDepartmentId('');}}}/>Include archived</label>}</div>
    {cycle&&<p className="coo-period">{cycle.name}: {cycle.start} to {cycle.end}{cycle.end<today?' · Completed period':cycle.start>today?' · Upcoming period':''}{cycle.parentId?` · Part of ${name('cycles',cycle.parentId)}`:''}</p>}
    {error&&!editor&&<div role="alert" className="coo-error">{error}</div>}{notice&&<p role="status" className="coo-notice">{notice}</p>}
    {!state.departments.length&&<section className="coo-onboard"><h2>Build your operating rhythm.</h2><p>Start with Manufacturing, Sales & Marketing, and Sourcing & Parts. Add departments, set a planning cycle, then define the measures that matter. Targets and actuals start empty.</p>{canWrite&&<button className="coo-primary" disabled={busy} onClick={()=>mutate({action:'setup'})}>Set up starting departments</button>}</section>}
    {view==='targets'&&<CooTargets state={state} cycle={cycle} departments={departments} query={query} canWrite={canWrite} open={open} onDetails={(kind,id)=>setDetail({kind,id})} onCycle={setCycleId}/>}
    {view==='overview'&&<>
      <div className="coo-section-head"><div><h2>Are we going to hit the plan?</h2><p>Compare actuals with agreed checkpoints, then see the forecast and constraints behind the gap.</p></div><button className="coo-primary" onClick={()=>setView('reviews')}>Run weekly review</button></div>
      <div className="coo-operating-summary">{[['','All measures'],['on-track','On track'],['off-track','Off track'],['at-risk','At risk'],['missing','Updates / plans needed']].map(([id,label])=><button className={statusFilter===id?'selected':''} key={id} onClick={()=>setStatusFilter(id)}>{label}<strong>{activeMetrics.filter(m=>{const h=metricHealth(state,m,today);return !id||id==='missing'?(!id||['no-data','stale','no-plan','no-forecast'].includes(h.status)):h.status===id;}).length}</strong></button>)}</div>
      <CooOperating state={state} metrics={metrics.filter(m=>!statusFilter||(statusFilter==='missing'?['no-data','stale','no-plan','no-forecast'].includes(metricHealth(state,m,today).status):metricHealth(state,m,today).status===statusFilter))} today={today} onDetails={(kind,id)=>setDetail({kind,id})} onUpdate={m=>open('metric',m,'checkin')} onConstraint={m=>open('constraint',null,'save',{cycleId:m.cycleId,departmentId:m.departmentId,metricIds:[m.id]})}/>
      <section className="coo-related"><h3>Business reporting</h3><p>Import the cached monthly financial forecast in Plan, or define custom operational checkpoints. Actuals and expected finishes are entered in Update progress.</p><div className="coo-row-actions"><button onClick={()=>setActiveTab('dashboard-cfo')}>Business dashboard</button><button onClick={()=>setActiveTab('dashboard-forecast')}>Financial forecast</button><button onClick={()=>setActiveTab('dashboard-dealers')}>Dealer performance</button></div></section>
    </>}
    {view==='plan'&&planView==='strategy'&&<>
      <div className="coo-section-head"><div><h2>Strategy & OKRs</h2><p>Connect company priorities to department outcomes and measurable key results.</p></div>{canWrite&&<button className="coo-primary" onClick={()=>open('objective',null,'save',{departmentId:''})}>Add objective</button>}</div>
      <div className="coo-objectives">{objectives.map(o=>{const p=objectiveProgress(state,o,today),krs=state.metrics.filter(m=>(!m.archived||o.archived)&&m.kind==='kr'&&m.objectiveId===o.id);return <article className="coo-objective" key={o.id}><div className="coo-section-head"><div><span className="coo-context">{name('departments',o.departmentId)} · {name('cycles',o.cycleId)}</span><h3>{o.title}{o.archived?' (archived)':''}</h3><p>{o.owner}</p></div><div className="coo-progress-label">{p.progress===null?'—':`${Math.round(p.progress*100)}%`}<small>{p.reported}/{p.total} key results reported</small></div></div>{o.parentId&&<button className="coo-link" onClick={()=>setDetail({kind:'objective',id:o.parentId})}>Supports: {name('objectives',o.parentId)}</button>}<p className="coo-description">{o.description}</p><progress max="1" value={p.progress||0} aria-label={`${o.title} progress`}/>{krs.map(m=>{const h=metricHealth(state,m,today);return <div className="coo-kr" key={m.id}><button className="coo-link" onClick={()=>setDetail({kind:'metric',id:m.id})}>{m.title}</button><span>{formatValue(h.value,m.unit)} / {formatValue(m.target,m.unit)}</span><Badge status={h.status}/></div>;})}{!krs.length&&<p className="coo-hint">Add measurable key results to track this objective.</p>}<div className="coo-section-head">{editButtons('objective',o)}{canWrite&&!o.archived&&<button onClick={()=>open('metric',null,'save',{objectiveId:o.id,cycleId:o.cycleId,departmentId:o.departmentId||defaults.departmentId,kind:'kr'})}>Add key result</button>}</div></article>;})}</div>
      {!objectives.length&&<Empty>Create a company objective, then align department objectives and key results to it.</Empty>}<p className="coo-hint">Objective progress is the equal-weight average of its direct key results. Unreported results count as zero; linked department objectives remain separately visible.</p>
    </>}
    {view==='plan'&&planView==='scorecards'&&<>
      <div className="coo-section-head"><div><h2>Measures & checkpoints</h2><p>Keep the definition, target, actual, and accountable owner together.</p></div><div className="coo-row-actions"><button onClick={exportCsv} disabled={!filteredMetrics.length}>Export CSV</button>{canWrite&&<button className="coo-primary" onClick={()=>open('metric')}>Add metric</button>}</div></div>
      <label className="coo-status-filter">Health<select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">All statuses</option>{['on-track','at-risk','off-track','stale','no-data','no-plan','no-forecast','not-started'].map(s=><option key={s} value={s}>{LABELS[s]}</option>)}</select></label>
      <div className="coo-table-wrap"><table className="coo-table"><thead><tr><th>Measure / owner</th><th>Department</th><th>Actual</th><th>Target</th><th>Trend</th><th>Health</th><th>Last update</th><th>Actions</th></tr></thead><tbody>{filteredMetrics.map(m=>{const h=metricHealth(state,m,today);return <tr key={m.id}><td><strong>{m.title}{m.archived?' (archived)':''}</strong><small>{m.owner} · {m.kind==='kr'?'Key result':'KPI'} · {name('cycles',m.cycleId)}</small></td><td>{name('departments',m.departmentId)}</td><td className="coo-number">{formatValue(h.value,m.unit)}</td><td>{m.direction==='increase'?'≥':'≤'} {formatValue(m.target,m.unit)}</td><td><Trend state={state} item={m}/></td><td><Badge status={h.status}/></td><td>{h.latest?.date||'—'}<small>Every {m.cadence} days</small></td><td>{editButtons('metric',m)}</td></tr>;})}</tbody></table></div>{!filteredMetrics.length&&<Empty>No metrics match this scope. Add a metric or change the filters.</Empty>}
      <p className="coo-hint">Trend: up to 12 reporting dates; dashed line marks the target. “Update due” means the latest actual is older than the reporting cadence. Ended cycles are assessed at their end date.</p>
    </>}
    {view==='constraints'&&<>
      <div className="coo-section-head"><div><h2>Constraints & actions</h2><p>One record for each constraint, with the affected outcomes and the work to resolve it.</p></div><div className="coo-row-actions"><button onClick={()=>open('initiative')}>Add initiative / action</button><button className="coo-primary" onClick={()=>open('constraint')}>Add constraint</button></div></div>
      <ConstraintList state={state} constraints={constraints} today={today} onDetails={(kind,id)=>setDetail({kind,id})} onEdit={c=>open('constraint',c)} onUpdate={c=>open('constraint',c,'checkin')} onAction={c=>open('initiative',null,'save',{type:'action',constraintId:c.id,cycleId:c.cycleId,departmentId:c.departmentId})}/>
      <h3 className="coo-space-top">Initiatives, milestones & actions</h3>
      <div className="coo-board">{[['planned','Planned'],['on-track','In progress'],['attention','Needs attention'],['done','Done']].map(([s,label])=>{const items=initiatives.filter(i=>{const h=initiativeHealth(state,i,today);return s==='attention'?['at-risk','blocked','overdue'].includes(h.status):h.status===s;});return <section key={s} className="coo-lane"><h3>{label}<span>{items.length}</span></h3>{items.map(i=>{const h=initiativeHealth(state,i,today),dep=state.initiatives.find(x=>x.id===i.dependencyId);return <article className="coo-work" key={i.id}><span className="coo-context">{i.type||'initiative'} · {name('departments',i.departmentId)}</span><h4>{i.title}{i.archived?' (archived)':''}</h4><p>{i.owner} · Due {i.dueDate}</p><Badge status={h.status}/>{i.constraintId&&<button className="coo-link" onClick={()=>setDetail({kind:'constraint',id:i.constraintId})}>Resolves: {name('constraints',i.constraintId)}</button>}{i.objectiveId&&<p>Objective: {name('objectives',i.objectiveId)}</p>}{i.parentInitiativeId&&<p>Milestone of: {name('initiatives',i.parentInitiativeId)}</p>}{dep&&<p className="coo-dependency">Depends on: {dep.title} ({LABELS[initiativeHealth(state,dep,today).reportedStatus]})</p>}{h.latest?.blocker&&<p className="coo-blocker">{h.latest.blocker}</p>}{editButtons('initiative',i)}</article>;})}{!items.length&&<p className="coo-hint">No commitments here.</p>}</section>;})}</div>
    </>}
    {view==='reviews'&&<>
      <div className="coo-section-head"><div><h2>Weekly review</h2><p>Review exceptions, record decisions, and leave with clear commitments.</p></div>{canWrite&&<button className="coo-primary" onClick={()=>open('review',null,'save',{departmentId})}>Record review</button>}</div>
      <section className="coo-panel"><h3>Review agenda <span className="coo-count">{exceptions.length}</span></h3>{exceptions.map(x=><div className="coo-agenda" key={x.item.id}><Badge status={x.status}/><div><strong>{x.item.title}</strong><p>{x.item.owner}{x.kind==='metric'?` · Actual ${formatValue(x.value,x.item.unit)} · Planned ${formatValue(x.planned,x.item.unit)} · Expected finish ${formatValue(x.forecast,x.item.unit)} · Goal ${formatValue(x.item.target,x.item.unit)}`:''}{x.item.decision?` · Decision: ${x.item.decision}`:''}{x.latest?.blocker?` · ${x.latest.blocker}`:''}</p></div>{editButtons(x.kind,x.item)}</div>)}{!exceptions.length&&<Empty>No exceptions in this scope. Use the review to record decisions and department updates.</Empty>}</section>
      <h3 className="coo-space-top">Review history</h3>{[...reviews].sort((a,b)=>b.date.localeCompare(a.date)).map(r=><article className="coo-review" key={r.id}><div className="coo-section-head"><div><span className="coo-context">{r.date} · {name('departments',r.departmentId)} · {r.owner}</span><h3>{r.title}</h3></div>{editButtons('review',r)}</div><p>{r.description}</p>{r.decisions&&<div className="coo-decision"><strong>Decisions</strong><p>{r.decisions}</p></div>}{r.lessons&&<p><strong>Lessons:</strong> {r.lessons}</p>}<p className="coo-hint">{r.snapshot?.length||0} measures and {r.constraintSnapshot?.length||0} constraints captured · {state.initiatives.filter(i=>i.reviewId===r.id).length} follow-up commitments</p>{canWrite&&!r.archived&&<button onClick={()=>open('initiative',null,'save',{type:'action',reviewId:r.id,cycleId:r.cycleId,departmentId:r.departmentId||defaults.departmentId})}>Assign follow-up</button>}</article>)}{!reviews.length&&<Empty>Saved reviews preserve the discussion, decisions, lessons, and scorecard at the time.</Empty>}
    </>}
    {view==='planning'&&<>
      <div className="coo-section-head"><div><h2>Departments & planning cycles</h2><p>Shape the workspace around your organization and planning rhythm.</p></div></div>
      <div className="coo-overview-grid"><section className="coo-panel"><div className="coo-section-head"><h3>Departments</h3>{canWrite&&<button onClick={()=>open('department')}>Add department</button>}</div>{state.departments.filter(d=>includeArchived||!d.archived).map(d=><article className="coo-config-row" key={d.id}><strong>{d.name}{d.archived?' (archived)':''}</strong><p>{d.owner||'No owner assigned'}</p><p>{d.description}</p>{editButtons('department',d)}</article>)}</section><section className="coo-panel"><div className="coo-section-head"><h3>Planning cycles</h3>{canWrite&&<button onClick={()=>open('cycle')}>Add cycle</button>}</div>{state.cycles.filter(c=>includeArchived||!c.archived).map(c=><article className="coo-config-row" key={c.id}><strong>{c.name}{c.archived?' (archived)':''}</strong><p>{c.start} — {c.end}</p>{c.parentId&&<p>Part of {name('cycles',c.parentId)}</p>}<p>{c.description}</p>{editButtons('cycle',c)}</article>)}{!state.cycles.length&&<Empty>Add an annual cycle, quarterly cycles within it, and monthly cycles within each quarter. Past cycles remain available for comparison.</Empty>}</section></div>
    </>}
    {detailItem&&<Detail item={detailItem} kind={detail.kind} state={state} name={name} canWrite={canWrite} onClose={()=>setDetail(null)} onEdit={()=>{setDetail(null);open(detail.kind,detailItem);}} onCheckin={()=>{setDetail(null);open(detail.kind,detailItem,'checkin');}} onArchive={()=>{setDetail(null);archive(detail.kind,detailItem);}} onCarry={()=>{setDetail(null);open(detail.kind,null,'save',{...detailItem,id:undefined,cycleId:'',parentId:'',objectiveId:'',dependencyId:'',parentInitiativeId:'',reviewId:'',constraintId:'',plan:[],planSource:'',dueDate:'',type:detailItem.type==='milestone'?'initiative':detailItem.type});}} onMilestone={()=>{setDetail(null);open('initiative',null,'save',{type:'milestone',parentInitiativeId:detailItem.id,cycleId:detailItem.cycleId,departmentId:detailItem.departmentId,objectiveId:detailItem.objectiveId});}}/>}
    {editor&&<CooEditor key={`${editor.kind}-${editor.item?.id||'new'}-${editor.mode}`} editor={editor} state={state} busy={busy||loading} error={error} onRefresh={load} onClose={()=>{setEditor(null);setError('');}} onSave={mutate}/>}
  </div>;
}
function Detail({item,kind,state,name,canWrite,onClose,onEdit,onCheckin,onArchive,onMilestone,onCarry}) {
  const ref=useRef(null);useEffect(()=>{const previous=document.activeElement;ref.current.showModal();return()=>previous?.focus?.();},[]);
  const history=[...state.checkins].reverse().filter(c=>c.kind===kind&&c.entityId===item.id).sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt.localeCompare(a.createdAt));
  return <dialog className="coo-dialog coo-detail" ref={ref} onCancel={e=>{e.preventDefault();onClose();}} aria-labelledby="coo-detail-title"><header><div><p>{kind}</p><h2 id="coo-detail-title">{item.title||item.name}</h2></div><button onClick={onClose} aria-label="Close details">×</button></header><div className="coo-detail-body"><p>{item.owner||'No owner assigned'}{item.cycleId?` · ${name('cycles',item.cycleId)}`:''}</p><p>{item.description||'No description added.'}</p>{kind==='constraint'&&<><p><strong>Business impact:</strong> {item.impact||'Not recorded'}</p><p><strong>Decision needed:</strong> {item.decision||'None recorded'}</p><p>Resolution due: {item.dueDate}</p><p>Affected: {[...(item.metricIds||[]).map(id=>name('metrics',id)),...(item.objectiveIds||[]).map(id=>name('objectives',id))].join(', ')}</p></>}{item.source&&<p><strong>Source:</strong> {item.source}</p>}{kind==='metric'&&<p>Baseline {formatValue(item.baseline,item.unit)} · Target {formatValue(item.target,item.unit)} · Update every {item.cadence} days</p>}{kind==='metric'&&item.plan?.length>0&&<><h3>Original plan</h3>{item.plan.map(p=><div className="coo-kr" key={p.date}><span>{p.date}</span><strong>{formatValue(p.value,item.unit)}</strong></div>)}</>}{item.decisions&&<p><strong>Decisions:</strong> {item.decisions}</p>}{item.lessons&&<p><strong>Lessons:</strong> {item.lessons}</p>}{item.snapshot&&<><h3>Scorecard at review</h3>{item.snapshot.map(m=><div className="coo-kr" key={m.id}><strong>{m.title}</strong><span>Actual {formatValue(m.value,m.unit)} · Planned {formatValue(m.planned,m.unit)} · Forecast {formatValue(m.forecast,m.unit)} · Goal {formatValue(m.target,m.unit)}</span><Badge status={m.status}/></div>)}</>}
      {item.constraintSnapshot&&<><h3>Constraints at review</h3>{item.constraintSnapshot.map(c=><div className="coo-kr" key={c.id}><strong>{c.title}</strong><span>{c.owner} · {c.decision||c.impact}</span><Badge status={c.status}/></div>)}</>}
      {['metric','initiative','constraint'].includes(kind)&&<><h3>Check-in history</h3>{!history.length&&<Empty>No check-ins recorded yet.</Empty>}{history.map(c=><article className="coo-history" key={c.id}><strong>{c.date} · {kind==='metric'?formatValue(c.value,item.unit):LABELS[c.status]}</strong>{kind==='metric'&&<p>Expected finish: {formatValue(c.forecast,item.unit)} · Goal at update: {formatValue(c.target,item.unit)}</p>}<p>{c.note}</p>{c.evidence&&<p><strong>Evidence:</strong> {c.evidence}</p>}{c.numerator!=null&&<p>Calculation: {c.numerator} ÷ {c.denominator}{item.measurement==='percentage'?' × 100':''}</p>}{c.decision!==undefined&&<p><strong>Decision needed:</strong> {c.decision||'None'}</p>}{c.blocker&&<p><strong>Blocker:</strong> {c.blocker}</p>}{c.nextStep&&<p><strong>Next step:</strong> {c.nextStep}</p>}<small>Recorded {new Date(c.createdAt).toLocaleString()} · {c.createdBy}</small></article>)}</>}
      <p className="coo-hint">Last edited {new Date(item.updatedAt).toLocaleString()} · {item.updatedBy}</p>
    </div><footer>{canWrite&&['objective','metric','initiative'].includes(kind)&&<button onClick={onCarry}>Plan in another cycle</button>}{canWrite&&!item.archived&&<><button className="coo-danger" onClick={onArchive}>Archive</button>{kind!=='review'&&<button onClick={onEdit}>Edit</button>}{kind==='initiative'&&!item.parentInitiativeId&&<button onClick={onMilestone}>Add milestone</button>}{['metric','initiative','constraint'].includes(kind)&&<button className="coo-primary" onClick={onCheckin}>Update progress</button>}</>}<button onClick={onClose}>Close</button></footer></dialog>;
}
