import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { apiJson } from '../../lib/api.js';
import { dayString, emptyWorkspace, metricHealth, objectiveProgress, initiativeHealth, formatValue, scorecardCsv, LABELS } from '../../lib/coo.js';
import CooEditor from './CooEditor.jsx';
import './coo.css';
const VIEWS=[['overview','Overview'],['strategy','Strategy & OKRs'],['scorecards','Scorecards'],['initiatives','Initiatives'],['reviews','Operating reviews'],['planning','Departments & cycles']];
const collections={department:'departments',cycle:'cycles',objective:'objectives',metric:'metrics',initiative:'initiatives',review:'reviews'};
const Badge=({status})=><span className={`coo-badge coo-${status}`}>{LABELS[status]||status}</span>;
const Empty=({children})=><div className="coo-empty">{children}</div>;
function Trend({state,item}) {
  const points=state.checkins.filter(c=>c.kind==='metric'&&c.entityId===item.id).sort((a,b)=>a.date.localeCompare(b.date)||a.createdAt.localeCompare(b.createdAt));
  const unique=[...new Map(points.map(c=>[c.date,c])).values()].slice(-12);
  if(unique.length<2)return <span className="coo-muted">Need 2 updates</span>;
  const low=Math.min(item.target,...unique.map(c=>c.value)),high=Math.max(item.target,...unique.map(c=>c.value));
  const y=v=>32-(v-low)/(high-low||1)*26;
  return <svg className="coo-trend" viewBox="0 0 116 38" role="img" aria-label={`Last ${unique.length} updates, ${formatValue(unique[0].value,item.unit)} to ${formatValue(unique.at(-1).value,item.unit)}`}><line x1="2" x2="114" y1={y(item.target)} y2={y(item.target)} stroke="#aaa" strokeDasharray="3 3"/><polyline fill="none" stroke="currentColor" strokeWidth="2" points={unique.map((c,i)=>`${3+i*110/(unique.length-1)},${y(c.value)}`).join(' ')}/></svg>;
}
export default function CooWorkspace({setActiveTab}) {
  const [data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
  const [view,setView]=useState('overview'),[cycleId,setCycleId]=useState(''),[departmentId,setDepartmentId]=useState(''),[query,setQuery]=useState(''),[statusFilter,setStatusFilter]=useState('');
  const [editor,setEditor]=useState(null),[detail,setDetail]=useState(null),[notice,setNotice]=useState(''),[includeArchived,setIncludeArchived]=useState(false);
  const lock=useRef(false),initialized=useRef(false);
  const load=useCallback(async()=>{if(lock.current)return;setLoading(true);setError('');try{const result=await apiJson('/api/coo-workspace');setData(result);if(!initialized.current){const today=dayString();const cycles=result.state.cycles.filter(c=>!c.archived);setCycleId(cycles.find(c=>c.start<=today&&c.end>=today&&c.parentId)?.id||cycles.find(c=>c.start<=today&&c.end>=today)?.id||cycles.at(-1)?.id||'');initialized.current=true;}}catch(e){setError(e.message);}finally{setLoading(false);}},[]);
  useEffect(()=>{load();},[load]);
  const state=useMemo(()=>({...emptyWorkspace(),...data?.state}),[data]);
  const today=dayString(),canWrite=!!data?.canWrite;
  const cycle=state.cycles.find(c=>c.id===cycleId);
  const visible=item=>(includeArchived||!item.archived)&&(!cycleId||item.cycleId===cycleId)&&(!departmentId||item.departmentId===departmentId)&&(!query||`${item.title} ${item.owner} ${item.description}`.toLowerCase().includes(query.toLowerCase()));
  const metrics=state.metrics.filter(visible),objectives=state.objectives.filter(visible),initiatives=state.initiatives.filter(visible),reviews=state.reviews.filter(visible);
  const departments=state.departments.filter(d=>!d.archived&&(!departmentId||d.id===departmentId));
  const name=(key,id,fallback='Company-wide')=>state[key].find(x=>x.id===id)?.name||state[key].find(x=>x.id===id)?.title||fallback;
  const defaults={cycleId:cycle?.archived?'':cycleId,departmentId:departmentId||state.departments.find(d=>!d.archived)?.id||''};
  const open=(kind,item,mode='save',extra={})=>{setError('');setEditor({kind,item,mode,defaults:{...defaults,...extra}});};
  const mutate=async(command)=>{
    if(lock.current||loading)return false;lock.current=true;setBusy(true);setError('');setNotice('');
    try{const result=await apiJson('/api/coo-workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:data.revision,command})});setData(result);setEditor(null);setNotice(command.action==='archive'?'Archived. History is preserved.':command.action==='checkin'?'Check-in saved.':'Saved to the shared workspace.');if(command.kind==='cycle'&&!command.id)setCycleId(result.state.cycles.at(-1).id);return true;}
    catch(e){setError(e.message);return false;}finally{lock.current=false;setBusy(false);}
  };
  const archive=(kind,item)=>{if(window.confirm(`Archive “${item.name||item.title}”? Its history will remain available.`))mutate({action:'archive',kind,id:item.id,expectedVersion:item.version||1});};
  const editButtons=(kind,item)=><div className="coo-row-actions"><button onClick={()=>setDetail({kind,id:item.id})}>Details</button>{canWrite&&!item.archived&&<>{kind!=='review'&&<button onClick={()=>open(kind,item)}>Edit</button>}{['metric','initiative'].includes(kind)&&<button onClick={()=>open(kind,item,'checkin')}>Check in</button>}</>}</div>;
  const activeMetrics=metrics.filter(m=>!m.archived),activeInitiatives=initiatives.filter(i=>!i.archived);
  const exceptions=[...activeMetrics.map(item=>({kind:'metric',item,...metricHealth(state,item,today)})),...activeInitiatives.map(item=>({kind:'initiative',item,...initiativeHealth(state,item,today)}))].filter(x=>['at-risk','off-track','stale','no-data','blocked','overdue'].includes(x.status));
  const filteredMetrics=metrics.filter(m=>!statusFilter||metricHealth(state,m,today).status===statusFilter);
  const detailItem=detail&&state[collections[detail.kind]].find(i=>i.id===detail.id);
  const exportCsv=()=>{const url=URL.createObjectURL(new Blob([scorecardCsv(state,filteredMetrics,today)],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download=`campfire-scorecard-${today}.csv`;a.click();URL.revokeObjectURL(url);};
  if(!data)return <div className="coo-page">{loading?<p role="status">Loading COO workspace…</p>:<div className="coo-error" role="alert">{error}<button onClick={load}>Retry</button></div>}</div>;
  return <div className="coo-page">
    <header className="coo-head"><div><h1>COO workspace</h1><p>Set the direction. Track the commitments. Run the week.</p></div><div className="coo-head-actions"><span>{canWrite?'Shared workspace':'Read-only access'}</span><button onClick={load} disabled={loading||busy}>{loading?'Refreshing…':'Refresh'}</button></div></header>
    <nav className="coo-tabs" aria-label="COO sections">{VIEWS.map(([id,label])=><button key={id} aria-current={view===id?'page':undefined} className={view===id?'active':''} onClick={()=>{setView(id);setQuery('');setStatusFilter('');setIncludeArchived(false);}}>{label}</button>)}</nav>
    <div className="coo-toolbar"><label>Planning cycle<select value={cycleId} onChange={e=>setCycleId(e.target.value)}><option value="">All cycles</option>{state.cycles.filter(c=>!c.archived||includeArchived).map(c=><option key={c.id} value={c.id}>{c.name}{c.archived?' (archived)':''}</option>)}</select></label><label>Department<select value={departmentId} onChange={e=>setDepartmentId(e.target.value)}><option value="">All departments</option>{state.departments.filter(d=>!d.archived||includeArchived).map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label className="coo-search">Search<input type="search" placeholder="Title, owner, or description" value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="coo-checkbox"><input type="checkbox" checked={includeArchived} onChange={e=>{setIncludeArchived(e.target.checked);if(!e.target.checked){if(cycle?.archived)setCycleId('');if(state.departments.find(d=>d.id===departmentId)?.archived)setDepartmentId('');}}}/>Include archived</label></div>
    {cycle&&<p className="coo-period">{cycle.name}: {cycle.start} to {cycle.end}{cycle.end<today?' · Completed period':cycle.start>today?' · Upcoming period':''}{cycle.parentId?` · Part of ${name('cycles',cycle.parentId)}`:''}</p>}
    {error&&!editor&&<div role="alert" className="coo-error">{error}</div>}{notice&&<p role="status" className="coo-notice">{notice}</p>}
    {!state.departments.length&&<section className="coo-onboard"><h2>Build your operating rhythm.</h2><p>Start with Manufacturing, Sales & Marketing, and Sourcing & Parts. Add departments, set a planning cycle, then define the measures that matter. Targets and actuals start empty.</p>{canWrite&&<button className="coo-primary" disabled={busy} onClick={()=>mutate({action:'setup'})}>Set up starting departments</button>}</section>}
    {view==='overview'&&<>
      <div className="coo-section-head"><div><h2>The operating picture</h2><p>Exceptions and commitments across the selected scope.</p></div>{canWrite&&<button className="coo-primary" onClick={()=>open('review')}>Run an operating review</button>}</div>
      <div className="coo-summary"><div><strong>{activeMetrics.filter(m=>metricHealth(state,m,today).status==='on-track').length}<small> / {activeMetrics.length}</small></strong><span>Measures on track</span></div><div><strong>{exceptions.length}</strong><span>Items needing attention</span></div><div><strong>{activeInitiatives.filter(i=>initiativeHealth(state,i,today).reportedStatus==='done').length}<small> / {activeInitiatives.length}</small></strong><span>Commitments completed</span></div><div><strong>{objectives.filter(o=>!o.archived).length}</strong><span>Strategic objectives</span></div></div>
      <div className="coo-overview-grid"><section className="coo-panel"><h3>Department pulse</h3>{departments.map(d=>{const ms=activeMetrics.filter(m=>m.departmentId===d.id),ok=ms.filter(m=>metricHealth(state,m,today).status==='on-track').length;const risk=exceptions.filter(x=>x.item.departmentId===d.id).length;return <button className="coo-dept-row" key={d.id} onClick={()=>{setDepartmentId(d.id);setView('scorecards');}}><span><strong>{d.name}</strong><small>{d.owner||'Assign a department owner'}</small></span><span className="coo-pulse"><span style={{width:`${ms.length?ok/ms.length*100:0}%`}}/></span><span>{ms.length?`${ok}/${ms.length} on track`:'No measures yet'}<small>{risk?`${risk} needing attention`:'No exceptions recorded'}</small></span></button>;})}{!departments.length&&<Empty>Add a department to build its scorecard.</Empty>}</section>
      <section className="coo-panel"><h3>Needs your attention</h3>{exceptions.slice(0,8).map(x=><button className="coo-exception" key={x.item.id} onClick={()=>setDetail({kind:x.kind,id:x.item.id})}><Badge status={x.status}/><strong>{x.item.title}</strong><small>{x.item.owner} · {name('departments',x.item.departmentId)}</small>{x.latest?.blocker&&<p>{x.latest.blocker}</p>}</button>)}{!exceptions.length&&<Empty>{activeMetrics.length||activeInitiatives.length?'No exceptions in this scope.':'Add measures and commitments to surface exceptions here.'}</Empty>}{exceptions.length>8&&<p className="coo-hint">{exceptions.length-8} more items in Operating reviews.</p>}</section></div>
      <section className="coo-related"><h3>Existing business reporting</h3><p>Use these Campfire reports as sources for your check-ins. COO actuals are entered manually and are not automatically synced.</p><div className="coo-row-actions"><button onClick={()=>setActiveTab('dashboard-cfo')}>Business dashboard</button><button onClick={()=>setActiveTab('dashboard-dealers')}>Dealer performance</button><button onClick={()=>setActiveTab('sku-media-pacing')}>SKU media pacing</button></div></section>
    </>}
    {view==='strategy'&&<>
      <div className="coo-section-head"><div><h2>Strategy & OKRs</h2><p>Connect company priorities to department outcomes and measurable key results.</p></div>{canWrite&&<button className="coo-primary" onClick={()=>open('objective',null,'save',{departmentId:''})}>Add objective</button>}</div>
      <div className="coo-objectives">{objectives.map(o=>{const p=objectiveProgress(state,o,today),krs=state.metrics.filter(m=>(!m.archived||o.archived)&&m.kind==='kr'&&m.objectiveId===o.id);return <article className="coo-objective" key={o.id}><div className="coo-section-head"><div><span className="coo-context">{name('departments',o.departmentId)} · {name('cycles',o.cycleId)}</span><h3>{o.title}{o.archived?' (archived)':''}</h3><p>{o.owner}</p></div><div className="coo-progress-label">{p.progress===null?'—':`${Math.round(p.progress*100)}%`}<small>{p.reported}/{p.total} key results reported</small></div></div>{o.parentId&&<button className="coo-link" onClick={()=>setDetail({kind:'objective',id:o.parentId})}>Supports: {name('objectives',o.parentId)}</button>}<p className="coo-description">{o.description}</p><progress max="1" value={p.progress||0} aria-label={`${o.title} progress`}/>{krs.map(m=>{const h=metricHealth(state,m,today);return <div className="coo-kr" key={m.id}><button className="coo-link" onClick={()=>setDetail({kind:'metric',id:m.id})}>{m.title}</button><span>{formatValue(h.value,m.unit)} / {formatValue(m.target,m.unit)}</span><Badge status={h.status}/></div>;})}{!krs.length&&<p className="coo-hint">Add measurable key results to track this objective.</p>}<div className="coo-section-head">{editButtons('objective',o)}{canWrite&&!o.archived&&<button onClick={()=>open('metric',null,'save',{objectiveId:o.id,cycleId:o.cycleId,departmentId:o.departmentId||defaults.departmentId,kind:'kr'})}>Add key result</button>}</div></article>;})}</div>
      {!objectives.length&&<Empty>Create a company objective, then align department objectives and key results to it.</Empty>}<p className="coo-hint">Objective progress is the equal-weight average of its direct key results. Unreported results count as zero; linked department objectives remain separately visible.</p>
    </>}
    {view==='scorecards'&&<>
      <div className="coo-section-head"><div><h2>Department scorecards</h2><p>Keep the definition, target, actual, and accountable owner together.</p></div><div className="coo-row-actions"><button onClick={exportCsv} disabled={!filteredMetrics.length}>Export CSV</button>{canWrite&&<button className="coo-primary" onClick={()=>open('metric')}>Add metric</button>}</div></div>
      <label className="coo-status-filter">Health<select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">All statuses</option>{['on-track','at-risk','off-track','stale','no-data','not-started'].map(s=><option key={s} value={s}>{LABELS[s]}</option>)}</select></label>
      <div className="coo-table-wrap"><table className="coo-table"><thead><tr><th>Measure / owner</th><th>Department</th><th>Actual</th><th>Target</th><th>Trend</th><th>Health</th><th>Last update</th><th>Actions</th></tr></thead><tbody>{filteredMetrics.map(m=>{const h=metricHealth(state,m,today);return <tr key={m.id}><td><strong>{m.title}{m.archived?' (archived)':''}</strong><small>{m.owner} · {m.kind==='kr'?'Key result':'KPI'} · {name('cycles',m.cycleId)}</small></td><td>{name('departments',m.departmentId)}</td><td className="coo-number">{formatValue(h.value,m.unit)}</td><td>{m.direction==='increase'?'≥':'≤'} {formatValue(m.target,m.unit)}</td><td><Trend state={state} item={m}/></td><td><Badge status={h.status}/></td><td>{h.latest?.date||'—'}<small>Every {m.cadence} days</small></td><td>{editButtons('metric',m)}</td></tr>;})}</tbody></table></div>{!filteredMetrics.length&&<Empty>No metrics match this scope. Add a metric or change the filters.</Empty>}
      <p className="coo-hint">Trend: up to 12 reporting dates; dashed line marks the target. “Update due” means the latest actual is older than the reporting cadence. Ended cycles are assessed at their end date.</p>
    </>}
    {view==='initiatives'&&<>
      <div className="coo-section-head"><div><h2>Initiatives & commitments</h2><p>Move strategy into owned work, milestones, and follow-up actions.</p></div>{canWrite&&<button className="coo-primary" onClick={()=>open('initiative')}>Add initiative</button>}</div>
      <div className="coo-board">{[['planned','Planned'],['on-track','In progress'],['attention','Needs attention'],['done','Done']].map(([s,label])=>{const items=initiatives.filter(i=>{const h=initiativeHealth(state,i,today);return s==='attention'?['at-risk','blocked','overdue'].includes(h.status):h.status===s;});return <section key={s} className="coo-lane"><h3>{label}<span>{items.length}</span></h3>{items.map(i=>{const h=initiativeHealth(state,i,today),dep=state.initiatives.find(x=>x.id===i.dependencyId);return <article className="coo-work" key={i.id}><span className="coo-context">{i.type||'initiative'} · {name('departments',i.departmentId)}</span><h4>{i.title}{i.archived?' (archived)':''}</h4><p>{i.owner} · Due {i.dueDate}</p><Badge status={h.status}/>{i.objectiveId&&<p>Objective: {name('objectives',i.objectiveId)}</p>}{i.parentInitiativeId&&<p>Milestone of: {name('initiatives',i.parentInitiativeId)}</p>}{dep&&<p className="coo-dependency">Depends on: {dep.title} ({LABELS[initiativeHealth(state,dep,today).reportedStatus]})</p>}{h.latest?.blocker&&<p className="coo-blocker">{h.latest.blocker}</p>}{editButtons('initiative',i)}</article>;})}{!items.length&&<p className="coo-hint">No commitments here.</p>}</section>;})}</div>
    </>}
    {view==='reviews'&&<>
      <div className="coo-section-head"><div><h2>Operating reviews</h2><p>Review exceptions, record decisions, and leave with clear commitments.</p></div>{canWrite&&<button className="coo-primary" onClick={()=>open('review',null,'save',{departmentId})}>Record review</button>}</div>
      <section className="coo-panel"><h3>Review agenda <span className="coo-count">{exceptions.length}</span></h3>{exceptions.map(x=><div className="coo-agenda" key={x.item.id}><Badge status={x.status}/><div><strong>{x.item.title}</strong><p>{x.item.owner}{x.latest?.blocker?` · ${x.latest.blocker}`:''}</p></div>{editButtons(x.kind,x.item)}</div>)}{!exceptions.length&&<Empty>No exceptions in this scope. Use the review to record decisions and department updates.</Empty>}</section>
      <h3 className="coo-space-top">Review history</h3>{[...reviews].sort((a,b)=>b.date.localeCompare(a.date)).map(r=><article className="coo-review" key={r.id}><div className="coo-section-head"><div><span className="coo-context">{r.date} · {name('departments',r.departmentId)} · {r.owner}</span><h3>{r.title}</h3></div>{editButtons('review',r)}</div><p>{r.description}</p>{r.decisions&&<div className="coo-decision"><strong>Decisions</strong><p>{r.decisions}</p></div>}{r.lessons&&<p><strong>Lessons:</strong> {r.lessons}</p>}<p className="coo-hint">{r.snapshot?.length||0} measures captured · {state.initiatives.filter(i=>i.reviewId===r.id).length} follow-up commitments</p>{canWrite&&!r.archived&&<button onClick={()=>open('initiative',null,'save',{type:'action',reviewId:r.id,cycleId:r.cycleId,departmentId:r.departmentId||defaults.departmentId})}>Assign follow-up</button>}</article>)}{!reviews.length&&<Empty>Saved reviews preserve the discussion, decisions, lessons, and scorecard at the time.</Empty>}
    </>}
    {view==='planning'&&<>
      <div className="coo-section-head"><div><h2>Departments & planning cycles</h2><p>Shape the workspace around your organization and planning rhythm.</p></div></div>
      <div className="coo-overview-grid"><section className="coo-panel"><div className="coo-section-head"><h3>Departments</h3>{canWrite&&<button onClick={()=>open('department')}>Add department</button>}</div>{state.departments.filter(d=>includeArchived||!d.archived).map(d=><article className="coo-config-row" key={d.id}><strong>{d.name}{d.archived?' (archived)':''}</strong><p>{d.owner||'No owner assigned'}</p><p>{d.description}</p>{editButtons('department',d)}</article>)}</section><section className="coo-panel"><div className="coo-section-head"><h3>Planning cycles</h3>{canWrite&&<button onClick={()=>open('cycle')}>Add cycle</button>}</div>{state.cycles.filter(c=>includeArchived||!c.archived).map(c=><article className="coo-config-row" key={c.id}><strong>{c.name}{c.archived?' (archived)':''}</strong><p>{c.start} — {c.end}</p>{c.parentId&&<p>Part of {name('cycles',c.parentId)}</p>}<p>{c.description}</p>{editButtons('cycle',c)}</article>)}{!state.cycles.length&&<Empty>Add an annual cycle, then quarterly cycles within it. Past cycles remain available for comparison.</Empty>}</section></div>
    </>}
    {detailItem&&<Detail item={detailItem} kind={detail.kind} state={state} name={name} canWrite={canWrite} onClose={()=>setDetail(null)} onEdit={()=>{setDetail(null);open(detail.kind,detailItem);}} onCheckin={()=>{setDetail(null);open(detail.kind,detailItem,'checkin');}} onArchive={()=>{setDetail(null);archive(detail.kind,detailItem);}} onCarry={()=>{setDetail(null);open(detail.kind,null,'save',{...detailItem,id:undefined,cycleId:'',parentId:'',objectiveId:'',dependencyId:'',parentInitiativeId:'',reviewId:'',dueDate:'',type:detailItem.type==='milestone'?'initiative':detailItem.type});}} onMilestone={()=>{setDetail(null);open('initiative',null,'save',{type:'milestone',parentInitiativeId:detailItem.id,cycleId:detailItem.cycleId,departmentId:detailItem.departmentId,objectiveId:detailItem.objectiveId});}}/>}
    {editor&&<CooEditor key={`${editor.kind}-${editor.item?.id||'new'}-${editor.mode}`} editor={editor} state={state} busy={busy||loading} error={error} onRefresh={load} onClose={()=>{setEditor(null);setError('');}} onSave={mutate}/>}
  </div>;
}
function Detail({item,kind,state,name,canWrite,onClose,onEdit,onCheckin,onArchive,onMilestone,onCarry}) {
  const ref=useRef(null);useEffect(()=>{const previous=document.activeElement;ref.current.showModal();return()=>previous?.focus?.();},[]);
  const history=[...state.checkins].reverse().filter(c=>c.kind===kind&&c.entityId===item.id).sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt.localeCompare(a.createdAt));
  return <dialog className="coo-dialog coo-detail" ref={ref} onCancel={e=>{e.preventDefault();onClose();}} aria-labelledby="coo-detail-title"><header><div><p>{kind}</p><h2 id="coo-detail-title">{item.title||item.name}</h2></div><button onClick={onClose} aria-label="Close details">×</button></header><div className="coo-detail-body"><p>{item.owner||'No owner assigned'}{item.cycleId?` · ${name('cycles',item.cycleId)}`:''}</p><p>{item.description||'No description added.'}</p>{item.source&&<p><strong>Source:</strong> {item.source}</p>}{kind==='metric'&&<p>Baseline {formatValue(item.baseline,item.unit)} · Target {formatValue(item.target,item.unit)} · Update every {item.cadence} days</p>}{item.decisions&&<p><strong>Decisions:</strong> {item.decisions}</p>}{item.lessons&&<p><strong>Lessons:</strong> {item.lessons}</p>}{item.snapshot&&<><h3>Scorecard at review</h3>{item.snapshot.map(m=><div className="coo-kr" key={m.id}><strong>{m.title}</strong><span>{formatValue(m.value,m.unit)} / {formatValue(m.target,m.unit)}</span><Badge status={m.status}/></div>)}</>}
      {['metric','initiative'].includes(kind)&&<><h3>Check-in history</h3>{!history.length&&<Empty>No check-ins recorded yet.</Empty>}{history.map(c=><article className="coo-history" key={c.id}><strong>{c.date} · {kind==='metric'?formatValue(c.value,item.unit):LABELS[c.status]}</strong><p>{c.note}</p>{c.blocker&&<p><strong>Blocker:</strong> {c.blocker}</p>}{c.nextStep&&<p><strong>Next step:</strong> {c.nextStep}</p>}<small>Recorded {new Date(c.createdAt).toLocaleString()} · {c.createdBy}</small></article>)}</>}
      <p className="coo-hint">Last edited {new Date(item.updatedAt).toLocaleString()} · {item.updatedBy}</p>
    </div><footer>{canWrite&&['objective','metric','initiative'].includes(kind)&&<button onClick={onCarry}>Plan in another cycle</button>}{canWrite&&!item.archived&&<><button className="coo-danger" onClick={onArchive}>Archive</button>{kind!=='review'&&<button onClick={onEdit}>Edit</button>}{kind==='initiative'&&!item.parentInitiativeId&&<button onClick={onMilestone}>Add milestone</button>}{['metric','initiative'].includes(kind)&&<button className="coo-primary" onClick={onCheckin}>Record check-in</button>}</>}<button onClick={onClose}>Close</button></footer></dialog>;
}
