import React,{useCallback,useEffect,useRef,useState} from 'react';
import { crmRequest } from './client.js';
const labels={draft:'Draft',sending:'Sending — refresh to check',sent:'Sent',uncertain:'Needs review',failed:'Rejected by Gmail',confirmed_sent:'Manually confirmed sent',confirmed_not_sent:'Manually confirmed not sent'};
export default function CrmEmail({opportunity,canSend,onDirty,onBusy,onSent,navigationBlocked}) {
  const [emails,setEmails]=useState([]),[sender,setSender]=useState(''),[connected,setConnected]=useState(false),[draft,setDraft]=useState(null),[data,setData]=useState(null);
  const [error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[reviewed,setReviewed]=useState(false);
  const lock=useRef(false),live=useRef(true),draftRef=useRef(null);
  const dirty=!!draft&&draft.status==='draft'&&JSON.stringify(data)!==JSON.stringify(draft.data);
  const unresolved=emails.some(e=>e.editable&&['sending','uncertain'].includes(e.status));
  const load=useCallback(async()=>{const r=await crmRequest(`/api/crm-email?opportunityId=${opportunity.id}`);if(!live.current)return;setEmails(r.emails);setConnected(r.connected);setSender(r.sender);setReady(true);return r;},[opportunity.id]);
  useEffect(()=>{live.current=true;load().catch(e=>setError(e.message));return()=>{live.current=false;};},[load]);
  useEffect(()=>{onDirty(dirty);},[dirty,onDirty]);
  useEffect(()=>{onBusy(busy);},[busy,onBusy]);
  async function run(work){if(lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('');try{await work();}catch(e){if(live.current)setError(e.message);}finally{lock.current=false;if(live.current)setBusy(false);}}
  function select(email){if(dirty&&!window.confirm('Discard unsaved email edits?'))return;setDraft(email);draftRef.current=email;setData(email.data);setReviewed(false);setError('');setNotice('');}
  function newDraft(){const data={to:opportunity.data.contacts.find(c=>c.email)?.email||'',subject:'',body:''};select({id:crypto.randomUUID(),revision:0,status:'draft',data,editable:true});}
  async function save(){const result=await crmRequest('/api/crm-email',{action:'save',id:draft.id,opportunityId:opportunity.id,revision:draft.revision,data});if(!live.current)return;setDraft(result.email);draftRef.current=result.email;setData(result.email.data);setReviewed(false);setNotice('Draft saved.');await load();}
  async function send(){const result=await crmRequest('/api/crm-email',{action:'send',id:draft.id,opportunityId:opportunity.id,revision:draft.revision,sender});if(!live.current)return;setDraft(result.email);draftRef.current=result.email;setData(result.email.data);setReviewed(false);setNotice(result.email.status==='sent'?'Email sent through Gmail.':result.email.error||'The send has already been submitted. Refresh its status.');await load();onSent();}
  async function resolve(outcome){if(!window.confirm(outcome==='confirmed_sent'?'Confirm that you found this exact email in Gmail Sent? This records your manual check.':'Confirm that you checked Gmail Sent and this email was NOT sent? Only do this after verifying; another send could otherwise duplicate it.'))return;const result=await crmRequest('/api/crm-email',{action:'resolve',id:draft.id,opportunityId:opportunity.id,checkedGmail:true,outcome});setDraft(result.email);draftRef.current=result.email;await load();onSent();}
  const readOnly=busy||draft?.status!=='draft'||!draft?.editable||!canSend||opportunity.archived;
  return <section className="crm-detail-section crm-email"><div className="crm-section-heading"><div><h3>Email</h3><p>{connected?`Send from ${sender}`:'Connect your Gmail to send from Campfire.'}</p></div>{canSend&&<button disabled={busy||dirty||navigationBlocked} onClick={()=>run(async()=>{const r=await crmRequest('/api/auth/google',{purpose:'crm_email'});window.location.assign(r.url);})}>{connected?'Reconnect Gmail':'Connect Gmail'}</button>}</div>
    <p className="crm-muted">Replies and emails sent directly from Gmail are logged manually. Drafts are private; sent messages are visible to CRM users.</p>
    {error&&<div role="alert" className="crm-alert">{error}</div>}{notice&&<p role="status" className="crm-notice">{notice}</p>}
    <div className="crm-actions"><button disabled={busy} onClick={()=>run(async()=>{const r=await load();const updated=r?.emails.find(e=>e.id===draftRef.current?.id);if(updated&&(!dirty||updated.status!=='draft')){setDraft(updated);draftRef.current=updated;setData(updated.data);setReviewed(false);}})}>Refresh email status</button>{canSend&&!opportunity.archived&&<button disabled={busy||!ready||unresolved} onClick={newDraft}>+ Compose email</button>}</div>
    {unresolved&&<div className="crm-banner">An email needs review. Open the attempt below, check Gmail Sent, and record the outcome before composing another message.</div>}
    <ul className="crm-email-list">{emails.map(e=><li key={e.id}><button disabled={busy} onClick={()=>select(e)}><strong>{e.data.subject||'Untitled draft'}</strong><span>{e.data.to||'No recipient'} · {labels[e.status]}</span><small>{new Date(e.created_at).toLocaleString()}</small></button></li>)}</ul>
    {draft&&<div className="crm-composer"><header><strong>{labels[draft.status]}</strong><button disabled={busy} aria-label="Close email" onClick={()=>{if(!dirty||window.confirm('Discard unsaved email edits?')){setDraft(null);draftRef.current=null;setData(null);}}}>✕</button></header>
      <fieldset disabled={readOnly}><label>To<input type="email" maxLength={254} value={data.to} onChange={e=>{setData({...data,to:e.target.value});setReviewed(false);}}/></label><label>Subject<input maxLength={300} value={data.subject} onChange={e=>{setData({...data,subject:e.target.value});setReviewed(false);}}/></label><label>Message<textarea rows={7} maxLength={40000} value={data.body} onChange={e=>{setData({...data,body:e.target.value});setReviewed(false);}}/></label></fieldset>
      {draft.status==='draft'&&draft.editable&&canSend&&!opportunity.archived&&<><div className="crm-actions"><button disabled={busy} onClick={()=>run(save)}>{busy?'Working…':'Save draft'}</button><span className="crm-muted">{dirty?'Unsaved email changes':draft.revision?'Draft saved':'Save this draft before sending.'}</span></div><label className="crm-check"><input type="checkbox" checked={reviewed} disabled={busy||dirty||!draft.revision||!connected} onChange={e=>setReviewed(e.target.checked)}/>I reviewed the recipient and message. Send from {sender||'my connected Gmail'}.</label><button className="crm-primary" disabled={busy||dirty||!draft.revision||!connected||!reviewed||!data.to||!data.subject||!data.body} onClick={()=>run(send)}>Send email</button></>}
      {draft.error&&<p className="crm-alert">{draft.error}</p>}
      {draft.editable&&['sending','uncertain'].includes(draft.status)&&<div className="crm-resolution"><p>If the status has not resolved after two minutes, check Gmail Sent for this recipient, subject, and message. Record what you find below. Campfire will never automatically retry this attempt.</p><a href="https://mail.google.com/mail/u/0/#sent" target="_blank" rel="noreferrer">Open Gmail Sent</a><small>Make sure Gmail is showing {draft.sender||sender}.</small><div className="crm-actions"><button disabled={busy} onClick={()=>run(()=>resolve('confirmed_sent'))}>I verified it was sent</button><button disabled={busy} onClick={()=>run(()=>resolve('confirmed_not_sent'))}>I verified it was not sent</button></div></div>}
    </div>}
  </section>;
}
