import React,{useCallback,useEffect,useMemo,useRef,useState} from 'react';
import { CRM_STAGES,crmCsv,followUpState,isOpen,localDay,money } from '../../lib/crm.js';
import { crmRequest } from './client.js';
import OpportunityEditor from './OpportunityEditor.jsx';
import './crm.css';

export default function CrmWorkspace({connectionError}) {
  const [rows,setRows]=useState([]),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const [rights,setRights]=useState({}),[query,setQuery]=useState(''),[view,setView]=useState('pipeline'),[owner,setOwner]=useState(''),[selected,setSelected]=useState(null);
  const mutationLock=useRef(false),generation=useRef(0);
  const load=useCallback(async()=>{const n=++generation.current;setBusy(true);try{const result=await crmRequest('/api/crm');if(n!==generation.current)return;setRows(result.opportunities);setRights(result);setLoaded(true);setError('');}catch(e){if(n===generation.current)setError(e.message);}finally{if(n===generation.current)setBusy(false);}},[]);
  useEffect(()=>{load();return()=>{generation.current++;};},[load]);
  const update=useCallback(o=>setRows(old=>[o,...old.filter(r=>r.id!==o.id)]),[]);
  const today=localDay();
  const filtered=useMemo(()=>rows.filter(o=>(view==='archived'?o.archived:!o.archived)&&(!owner||o.data.owner===owner)&&`${o.data.title} ${o.data.company} ${o.data.contacts.map(c=>`${c.name} ${c.email}`).join(' ')}`.toLowerCase().includes(query.toLowerCase())),[rows,view,owner,query]);
  const followups=filtered.filter(isOpen).sort((a,b)=>(a.data.followUp||'0000').localeCompare(b.data.followUp||'0000')||a.data.company.localeCompare(b.data.company));
  const open=rows.filter(isOpen),due=open.filter(o=>!o.data.followUp||o.data.followUp<=today);
  async function move(id,stage) {
    if(mutationLock.current||!rights.canWrite)return;
    const row=rows.find(o=>o.id===id);if(!row||row.data.stage===stage)return;
    mutationLock.current=true;setBusy(true);setError('');
    try{const r=await crmRequest('/api/crm',{action:'stage',id,stage,revision:row.revision,requestId:crypto.randomUUID()});update(r.opportunity);}catch(e){setError(e.message);}finally{mutationLock.current=false;setBusy(false);}
  }
  function exportCsv(){const url=URL.createObjectURL(new Blob([crmCsv(filtered)],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`campfire-opportunities-${today}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  return <section className="crm">
    <header className="crm-header"><div><h1>Sales pipeline</h1><p>Keep the conversation moving.</p></div><div className="crm-actions"><button onClick={exportCsv} disabled={!loaded||!filtered.length}>Export CSV</button>{rights.canWrite&&<button className="crm-primary" disabled={busy} onClick={()=>setSelected({id:crypto.randomUUID(),isNew:true})}>+ New opportunity</button>}</div></header>
    <div className="crm-summary"><div><strong>{money(open.reduce((sum,o)=>sum+o.data.value,0))}</strong><span>Open pipeline · USD</span></div><div><strong>{open.length}</strong><span>Active opportunities</span></div><button onClick={()=>setView('followups')}><strong>{due.length}</strong><span>Follow-ups due</span></button><p>Replies stay in Gmail.<br/>Log the outcome here and set the next step.</p></div>
    {connectionError&&<div className="crm-alert" role="alert">{connectionError}</div>}
    {error&&<div className="crm-alert" role="alert">{error} <button onClick={load} disabled={busy}>Reload pipeline</button></div>}
    <div className="crm-toolbar"><div className="crm-tabs" aria-label="Pipeline view">{[['pipeline','Pipeline'],['followups','Follow-ups'],['archived','Archived']].map(([id,label])=><button key={id} aria-pressed={view===id} onClick={()=>setView(id)}>{label}</button>)}</div><div className="crm-filters"><input aria-label="Search opportunities" placeholder="Search company, contact, opportunity…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Filter by owner" value={owner} onChange={e=>setOwner(e.target.value)}><option value="">All owners</option>{[...new Set(rows.map(o=>o.data.owner))].sort().map(o=><option key={o}>{o}</option>)}</select><button onClick={load} disabled={busy} aria-label="Refresh pipeline">{busy?'Loading…':'Refresh'}</button></div></div>
    {!loaded?<div className="crm-empty">{error?'The pipeline could not be loaded. Retry using the button above.':'Loading opportunities…'}</div>:view==='pipeline'?<div className="crm-board">{CRM_STAGES.map(stage=>{const items=filtered.filter(o=>o.data.stage===stage.id);return <section className={`crm-column crm-stage-${stage.id}`} key={stage.id} onDragOver={e=>{if(rights.canWrite&&!busy)e.preventDefault();}} onDrop={e=>{e.preventDefault();move(e.dataTransfer.getData('text/plain'),stage.id);}} aria-label={stage.label}><header><h2>{stage.label} <span>{items.length}</span></h2><p>{money(items.reduce((sum,o)=>sum+o.data.value,0))}</p></header><div className="crm-cards">{items.map(o=><button className="crm-card" key={o.id} draggable={rights.canWrite&&!busy} onDragStart={e=>{e.dataTransfer.setData('text/plain',o.id);e.dataTransfer.effectAllowed='move';}} onClick={()=>setSelected(o)}><span className="crm-company">{o.data.company}</span><strong>{o.data.title}</strong><span className="crm-card-value">{money(o.data.value)} <small>{o.data.owner}</small></span>{isOpen(o)?<span className={`crm-next ${o.data.followUp<=today?'crm-due':''}`}><span>{o.data.nextAction||'Set a next action'}</span><small>{followUpState(o,today)} · {o.data.followUp||'No date'}</small></span>:<span className="crm-next">{stage.label}{o.data.closeDate?` · ${o.data.closeDate}`:''}</span>}</button>)}{!items.length&&<p className="crm-lane-empty">{stage.id==='new'&&!rows.length?'Add your first opportunity to get started.':'No opportunities'}</p>}</div></section>;})}</div>:<div className="crm-list">{(view==='followups'?followups:filtered).length?<table><thead><tr><th>Opportunity</th><th>Next action</th><th>Follow-up</th><th>Owner</th><th>Value</th><th></th></tr></thead><tbody>{(view==='followups'?followups:filtered).map(o=><tr key={o.id}><td><strong>{o.data.company}</strong><span>{o.data.title}</span></td><td>{o.data.nextAction||'—'}</td><td><span className={isOpen(o)&&o.data.followUp<=today?'crm-due':''}>{o.data.followUp||'—'}</span><small>{followUpState(o,today)}</small></td><td>{o.data.owner}</td><td>{money(o.data.value)}</td><td><button onClick={()=>setSelected(o)}>Open<span className="crm-sr-only"> {o.data.title}</span></button></td></tr>)}</tbody></table>:<div className="crm-empty">{view==='archived'?'No archived opportunities. Archived records can be restored here.':'No open opportunities match these filters.'}</div>}</div>}
    {selected&&<OpportunityEditor key={selected.id} initial={selected} canWrite={rights.canWrite} canSend={rights.canSend} onUpdate={update} onClose={()=>setSelected(null)}/>}
  </section>;
}
